dependencies {
	testIntegrationCompile group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.8"
	testIntegrationCompile group: "com.liferay", name: "com.liferay.dynamic.data.lists.api", version: "3.0.0"
	testIntegrationCompile group: "com.liferay", name: "com.liferay.dynamic.data.mapping.api", version: "4.0.0"
	testIntegrationCompile group: "com.liferay", name: "com.liferay.dynamic.data.mapping.test.util", version: "3.0.0"
	testIntegrationCompile group: "com.liferay", name: "com.liferay.portal.upgrade.api", version: "2.0.0"
	testIntegrationCompile group: "com.liferay", name: "com.liferay.registry.api", version: "2.0.0"
	testIntegrationCompile group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "3.0.0"
	testIntegrationCompile project(":private:apps:portal-workflow:portal-workflow-kaleo-forms-api")
	testIntegrationCompile project(":private:apps:portal-workflow:portal-workflow-kaleo-forms-service")
}