apply plugin: "com.liferay.spring.boot.defaults"
apply plugin: "io.spring.dependency-management"

ext["junit-jupiter.version"] = "5.8.2"
ext["log4j2.version"] = "2.17.0"

bootJar {
	enabled = false
}

dependencies {
	api project(configuration: "default", path: ":dxp:apps:osb:osb-asah:osb-asah-common")

	testIntegrationImplementation project(configuration: "default", path: ":dxp:apps:osb:osb-asah:osb-asah-test-util")
}

jar {
	enabled = true
}