/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.price.list.model.impl;

import com.liferay.commerce.price.list.model.CommercePriceListPriceModifierRel;
import com.liferay.commerce.price.list.model.CommercePriceListPriceModifierRelModel;
import com.liferay.commerce.price.list.model.CommercePriceListPriceModifierRelSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CommercePriceListPriceModifierRel service. Represents a row in the &quot;CPLPriceModifierRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CommercePriceListPriceModifierRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommercePriceListPriceModifierRelImpl}.
 * </p>
 *
 * @author Alessio Antonio Rendina
 * @see CommercePriceListPriceModifierRelImpl
 * @generated
 */
@JSON(strict = true)
public class CommercePriceListPriceModifierRelModelImpl
	extends BaseModelImpl<CommercePriceListPriceModifierRel>
	implements CommercePriceListPriceModifierRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce price list price modifier rel model instance should use the <code>CommercePriceListPriceModifierRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "CPLPriceModifierRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"CPLPriceModifierRelId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"commercePriceModifierId", Types.BIGINT},
		{"commercePriceListId", Types.BIGINT}, {"order_", Types.INTEGER},
		{"lastPublishDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CPLPriceModifierRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("commercePriceModifierId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("commercePriceListId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("order_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CPLPriceModifierRel (uuid_ VARCHAR(75) null,CPLPriceModifierRelId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,commercePriceModifierId LONG,commercePriceListId LONG,order_ INTEGER,lastPublishDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table CPLPriceModifierRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commercePriceListPriceModifierRel.order ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CPLPriceModifierRel.order_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.price.list.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.commerce.price.list.model.CommercePriceListPriceModifierRel"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.price.list.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.commerce.price.list.model.CommercePriceListPriceModifierRel"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.price.list.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.commerce.price.list.model.CommercePriceListPriceModifierRel"),
		true);

	public static final long COMMERCEPRICELISTID_COLUMN_BITMASK = 1L;

	public static final long COMMERCEPRICEMODIFIERID_COLUMN_BITMASK = 2L;

	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long ORDER_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CommercePriceListPriceModifierRel toModel(
		CommercePriceListPriceModifierRelSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		CommercePriceListPriceModifierRel model =
			new CommercePriceListPriceModifierRelImpl();

		model.setUuid(soapModel.getUuid());
		model.setCommercePriceListPriceModifierRelId(
			soapModel.getCommercePriceListPriceModifierRelId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCommercePriceModifierId(
			soapModel.getCommercePriceModifierId());
		model.setCommercePriceListId(soapModel.getCommercePriceListId());
		model.setOrder(soapModel.getOrder());
		model.setLastPublishDate(soapModel.getLastPublishDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CommercePriceListPriceModifierRel> toModels(
		CommercePriceListPriceModifierRelSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<CommercePriceListPriceModifierRel> models =
			new ArrayList<CommercePriceListPriceModifierRel>(soapModels.length);

		for (CommercePriceListPriceModifierRelSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.commerce.price.list.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.commerce.price.list.model.CommercePriceListPriceModifierRel"));

	public CommercePriceListPriceModifierRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commercePriceListPriceModifierRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommercePriceListPriceModifierRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commercePriceListPriceModifierRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommercePriceListPriceModifierRel.class;
	}

	@Override
	public String getModelClassName() {
		return CommercePriceListPriceModifierRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CommercePriceListPriceModifierRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry
				<String, Function<CommercePriceListPriceModifierRel, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommercePriceListPriceModifierRel, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(CommercePriceListPriceModifierRel)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CommercePriceListPriceModifierRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CommercePriceListPriceModifierRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CommercePriceListPriceModifierRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CommercePriceListPriceModifierRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CommercePriceListPriceModifierRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function
		<InvocationHandler, CommercePriceListPriceModifierRel>
			_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CommercePriceListPriceModifierRel.class.getClassLoader(),
			CommercePriceListPriceModifierRel.class, ModelWrapper.class);

		try {
			Constructor<CommercePriceListPriceModifierRel> constructor =
				(Constructor<CommercePriceListPriceModifierRel>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map
		<String, Function<CommercePriceListPriceModifierRel, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<CommercePriceListPriceModifierRel, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<CommercePriceListPriceModifierRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String,
					 Function<CommercePriceListPriceModifierRel, Object>>();
		Map<String, BiConsumer<CommercePriceListPriceModifierRel, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String,
					 BiConsumer<CommercePriceListPriceModifierRel, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel) {

					return commercePriceListPriceModifierRel.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public void accept(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel,
					Object uuidObject) {

					commercePriceListPriceModifierRel.setUuid(
						(String)uuidObject);
				}

			});
		attributeGetterFunctions.put(
			"commercePriceListPriceModifierRelId",
			new Function<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel) {

					return commercePriceListPriceModifierRel.
						getCommercePriceListPriceModifierRelId();
				}

			});
		attributeSetterBiConsumers.put(
			"commercePriceListPriceModifierRelId",
			new BiConsumer<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public void accept(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel,
					Object commercePriceListPriceModifierRelIdObject) {

					commercePriceListPriceModifierRel.
						setCommercePriceListPriceModifierRelId(
							(Long)commercePriceListPriceModifierRelIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel) {

					return commercePriceListPriceModifierRel.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public void accept(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel,
					Object companyIdObject) {

					commercePriceListPriceModifierRel.setCompanyId(
						(Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel) {

					return commercePriceListPriceModifierRel.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public void accept(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel,
					Object userIdObject) {

					commercePriceListPriceModifierRel.setUserId(
						(Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel) {

					return commercePriceListPriceModifierRel.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public void accept(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel,
					Object userNameObject) {

					commercePriceListPriceModifierRel.setUserName(
						(String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel) {

					return commercePriceListPriceModifierRel.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public void accept(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel,
					Object createDateObject) {

					commercePriceListPriceModifierRel.setCreateDate(
						(Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel) {

					return commercePriceListPriceModifierRel.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public void accept(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel,
					Object modifiedDateObject) {

					commercePriceListPriceModifierRel.setModifiedDate(
						(Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"commercePriceModifierId",
			new Function<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel) {

					return commercePriceListPriceModifierRel.
						getCommercePriceModifierId();
				}

			});
		attributeSetterBiConsumers.put(
			"commercePriceModifierId",
			new BiConsumer<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public void accept(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel,
					Object commercePriceModifierIdObject) {

					commercePriceListPriceModifierRel.
						setCommercePriceModifierId(
							(Long)commercePriceModifierIdObject);
				}

			});
		attributeGetterFunctions.put(
			"commercePriceListId",
			new Function<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel) {

					return commercePriceListPriceModifierRel.
						getCommercePriceListId();
				}

			});
		attributeSetterBiConsumers.put(
			"commercePriceListId",
			new BiConsumer<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public void accept(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel,
					Object commercePriceListIdObject) {

					commercePriceListPriceModifierRel.setCommercePriceListId(
						(Long)commercePriceListIdObject);
				}

			});
		attributeGetterFunctions.put(
			"order",
			new Function<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel) {

					return commercePriceListPriceModifierRel.getOrder();
				}

			});
		attributeSetterBiConsumers.put(
			"order",
			new BiConsumer<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public void accept(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel,
					Object orderObject) {

					commercePriceListPriceModifierRel.setOrder(
						(Integer)orderObject);
				}

			});
		attributeGetterFunctions.put(
			"lastPublishDate",
			new Function<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public Object apply(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel) {

					return commercePriceListPriceModifierRel.
						getLastPublishDate();
				}

			});
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			new BiConsumer<CommercePriceListPriceModifierRel, Object>() {

				@Override
				public void accept(
					CommercePriceListPriceModifierRel
						commercePriceListPriceModifierRel,
					Object lastPublishDateObject) {

					commercePriceListPriceModifierRel.setLastPublishDate(
						(Date)lastPublishDateObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getCommercePriceListPriceModifierRelId() {
		return _commercePriceListPriceModifierRelId;
	}

	@Override
	public void setCommercePriceListPriceModifierRelId(
		long commercePriceListPriceModifierRelId) {

		_commercePriceListPriceModifierRelId =
			commercePriceListPriceModifierRelId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCommercePriceModifierId() {
		return _commercePriceModifierId;
	}

	@Override
	public void setCommercePriceModifierId(long commercePriceModifierId) {
		_columnBitmask |= COMMERCEPRICEMODIFIERID_COLUMN_BITMASK;

		if (!_setOriginalCommercePriceModifierId) {
			_setOriginalCommercePriceModifierId = true;

			_originalCommercePriceModifierId = _commercePriceModifierId;
		}

		_commercePriceModifierId = commercePriceModifierId;
	}

	public long getOriginalCommercePriceModifierId() {
		return _originalCommercePriceModifierId;
	}

	@JSON
	@Override
	public long getCommercePriceListId() {
		return _commercePriceListId;
	}

	@Override
	public void setCommercePriceListId(long commercePriceListId) {
		_columnBitmask |= COMMERCEPRICELISTID_COLUMN_BITMASK;

		if (!_setOriginalCommercePriceListId) {
			_setOriginalCommercePriceListId = true;

			_originalCommercePriceListId = _commercePriceListId;
		}

		_commercePriceListId = commercePriceListId;
	}

	public long getOriginalCommercePriceListId() {
		return _originalCommercePriceListId;
	}

	@JSON
	@Override
	public int getOrder() {
		return _order;
	}

	@Override
	public void setOrder(int order) {
		_columnBitmask = -1L;

		_order = order;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		_lastPublishDate = lastPublishDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				CommercePriceListPriceModifierRel.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CommercePriceListPriceModifierRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommercePriceListPriceModifierRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CommercePriceListPriceModifierRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommercePriceListPriceModifierRelImpl
			commercePriceListPriceModifierRelImpl =
				new CommercePriceListPriceModifierRelImpl();

		commercePriceListPriceModifierRelImpl.setUuid(getUuid());
		commercePriceListPriceModifierRelImpl.
			setCommercePriceListPriceModifierRelId(
				getCommercePriceListPriceModifierRelId());
		commercePriceListPriceModifierRelImpl.setCompanyId(getCompanyId());
		commercePriceListPriceModifierRelImpl.setUserId(getUserId());
		commercePriceListPriceModifierRelImpl.setUserName(getUserName());
		commercePriceListPriceModifierRelImpl.setCreateDate(getCreateDate());
		commercePriceListPriceModifierRelImpl.setModifiedDate(
			getModifiedDate());
		commercePriceListPriceModifierRelImpl.setCommercePriceModifierId(
			getCommercePriceModifierId());
		commercePriceListPriceModifierRelImpl.setCommercePriceListId(
			getCommercePriceListId());
		commercePriceListPriceModifierRelImpl.setOrder(getOrder());
		commercePriceListPriceModifierRelImpl.setLastPublishDate(
			getLastPublishDate());

		commercePriceListPriceModifierRelImpl.resetOriginalValues();

		return commercePriceListPriceModifierRelImpl;
	}

	@Override
	public int compareTo(
		CommercePriceListPriceModifierRel commercePriceListPriceModifierRel) {

		int value = 0;

		if (getOrder() < commercePriceListPriceModifierRel.getOrder()) {
			value = -1;
		}
		else if (getOrder() > commercePriceListPriceModifierRel.getOrder()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CommercePriceListPriceModifierRel)) {
			return false;
		}

		CommercePriceListPriceModifierRel commercePriceListPriceModifierRel =
			(CommercePriceListPriceModifierRel)obj;

		long primaryKey = commercePriceListPriceModifierRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CommercePriceListPriceModifierRelModelImpl
			commercePriceListPriceModifierRelModelImpl = this;

		commercePriceListPriceModifierRelModelImpl._originalUuid =
			commercePriceListPriceModifierRelModelImpl._uuid;

		commercePriceListPriceModifierRelModelImpl._originalCompanyId =
			commercePriceListPriceModifierRelModelImpl._companyId;

		commercePriceListPriceModifierRelModelImpl._setOriginalCompanyId =
			false;

		commercePriceListPriceModifierRelModelImpl._setModifiedDate = false;

		commercePriceListPriceModifierRelModelImpl.
			_originalCommercePriceModifierId =
				commercePriceListPriceModifierRelModelImpl.
					_commercePriceModifierId;

		commercePriceListPriceModifierRelModelImpl.
			_setOriginalCommercePriceModifierId = false;

		commercePriceListPriceModifierRelModelImpl.
			_originalCommercePriceListId =
				commercePriceListPriceModifierRelModelImpl._commercePriceListId;

		commercePriceListPriceModifierRelModelImpl.
			_setOriginalCommercePriceListId = false;

		commercePriceListPriceModifierRelModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CommercePriceListPriceModifierRel> toCacheModel() {
		CommercePriceListPriceModifierRelCacheModel
			commercePriceListPriceModifierRelCacheModel =
				new CommercePriceListPriceModifierRelCacheModel();

		commercePriceListPriceModifierRelCacheModel.uuid = getUuid();

		String uuid = commercePriceListPriceModifierRelCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			commercePriceListPriceModifierRelCacheModel.uuid = null;
		}

		commercePriceListPriceModifierRelCacheModel.
			commercePriceListPriceModifierRelId =
				getCommercePriceListPriceModifierRelId();

		commercePriceListPriceModifierRelCacheModel.companyId = getCompanyId();

		commercePriceListPriceModifierRelCacheModel.userId = getUserId();

		commercePriceListPriceModifierRelCacheModel.userName = getUserName();

		String userName = commercePriceListPriceModifierRelCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			commercePriceListPriceModifierRelCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			commercePriceListPriceModifierRelCacheModel.createDate =
				createDate.getTime();
		}
		else {
			commercePriceListPriceModifierRelCacheModel.createDate =
				Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			commercePriceListPriceModifierRelCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			commercePriceListPriceModifierRelCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		commercePriceListPriceModifierRelCacheModel.commercePriceModifierId =
			getCommercePriceModifierId();

		commercePriceListPriceModifierRelCacheModel.commercePriceListId =
			getCommercePriceListId();

		commercePriceListPriceModifierRelCacheModel.order = getOrder();

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			commercePriceListPriceModifierRelCacheModel.lastPublishDate =
				lastPublishDate.getTime();
		}
		else {
			commercePriceListPriceModifierRelCacheModel.lastPublishDate =
				Long.MIN_VALUE;
		}

		return commercePriceListPriceModifierRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CommercePriceListPriceModifierRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry
				<String, Function<CommercePriceListPriceModifierRel, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommercePriceListPriceModifierRel, Object>
				attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply(
					(CommercePriceListPriceModifierRel)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CommercePriceListPriceModifierRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry
				<String, Function<CommercePriceListPriceModifierRel, Object>>
					entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommercePriceListPriceModifierRel, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(CommercePriceListPriceModifierRel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CommercePriceListPriceModifierRel>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _commercePriceListPriceModifierRelId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _commercePriceModifierId;
	private long _originalCommercePriceModifierId;
	private boolean _setOriginalCommercePriceModifierId;
	private long _commercePriceListId;
	private long _originalCommercePriceListId;
	private boolean _setOriginalCommercePriceListId;
	private int _order;
	private Date _lastPublishDate;
	private long _columnBitmask;
	private CommercePriceListPriceModifierRel _escapedModel;

}