hot.deploy.dependency.management.enabled=true
users.reminder.queries.enabled=false
terms.of.use.required=false
auth.token.check.enabled=false
auth.token.ignore.portlets=82,1_WAR_loopportlet
auto.login.hooks=com.liferay.portal.security.auth.RememberMeAutoLogin,com.liferay.portal.security.auth.BasicAuthHeaderAutoLogin
passwords.default.policy.change.required=false
dl.file.max.size=26214400

index.search.leading.wildcard.enabled=true