INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 321, timestamp '${today-1d}', 'USD', 321, 1, timestamp '${today}', timestamp '${today-2d}', null, 2, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (4, 123, timestamp '${today-2d}', 'USD', 123, 1, timestamp '${today}', timestamp '${today-3d}', null, 2, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (7, 123, timestamp '${today-3d}', 'USD', 123, 1, timestamp '${today}', timestamp '${today-6d}', null, 2, '10.0');

INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 123, timestamp '${today}', 'USD', 123, 1, timestamp '${today}', timestamp '${today}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (2, 123, timestamp '${today}', 'USD', 123, 1, timestamp '${today}', timestamp '${today-1d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 123, timestamp '${today-1d}', 'USD', 123, 1, timestamp '${today}', timestamp '${today-2d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 321, timestamp '${today-1d}', 'USD', 321, 1, timestamp '${today}', timestamp '${today-2d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (4, 123, timestamp '${today-2d}', 'USD', 123, 1, timestamp '${today}', timestamp '${today-3d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (7, 123, timestamp '${today-3d}', 'USD', 123, 1, timestamp '${today}', timestamp '${today-6d}', null, 1, '10.0');

INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 321, timestamp '${today-1d}', 'USD', 321, 1, timestamp '${today}', timestamp '${today-2d}', null, 0, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (4, 123, timestamp '${today-2d}', 'USD', 123, 1, timestamp '${today}', timestamp '${today-3d}', null, 0, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (7, 123, timestamp '${today-3d}', 'USD', 123, 1, timestamp '${today}', timestamp '${today-6d}', null, 0, '10.0');

INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (10, 123, timestamp '${today-2d}', 'EUR', 2, 1, timestamp '${today}', timestamp '${today-3d}', null, 123, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (17, 123, timestamp '${today-3d}', 'EUR', 2, 1, timestamp '${today}', timestamp '${today-6d}', null, 2, '10.0');

INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (10, 123, timestamp '${today-2d}', 'EUR', 2, 1, timestamp '${today}', timestamp '${today-3d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (17, 123, timestamp '${today-3d}', 'EUR', 2, 1, timestamp '${today}', timestamp '${today-6d}', null, 1, '10.0');

INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (18, 123, timestamp '${today-2d}', 'EUR', 2, 1, timestamp '${today}', timestamp '${today-3d}', null, 0, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (19, 123, timestamp '${today-3d}', 'EUR', 2, 1, timestamp '${today}', timestamp '${today-6d}', null, 0, '10.0');

INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (3, 123, timestamp '${today-7d}', 'USD', 123, 1, timestamp '${today}', timestamp '${today-7d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (3, 123, timestamp '${today-7d}', 'USD', 123, 1, timestamp '${today}', timestamp '${today-8d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (8, 123, timestamp '${today-8d}', 'USD', 123, 1, timestamp '${today}', timestamp '${today-9d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 123, timestamp '${today-10d}', 'USD', 123, 1, timestamp '${today}', timestamp '${today-11d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 123, timestamp '${today-11d}', 'USD', 123, 1, timestamp '${today}', timestamp '${today-14d}', null, 1, '10.0');