allowed.sender.names[brianchandotcom]=\
    achaparro,\
    alecsloan,\
    alexcandidos,\
    amosfong,\
    andrea-ale-sbarra,\
    austinchiang,\
    brianwulbern,\
    brookedalton,\
    carolmoreschi,\
    caustin582,\
    cgoncas,\
    christianstokes,\
    codyhoag,\
    commando18,\
    csabaturcsan,\
    csierra,\
    cvanut,\
    david-gutierrez-mesa,\
    dejuknow,\
    dellawang,\
    dgarciasarai,\
    dougwong,\
    drewbrokke,\
    dsitu,\
    ethanbustad,\
    fabiodiegomastrorilli,\
    gaborlovasdotcom,\
    gianmarcobrunialti,\
    ginsonren,\
    hanlf,\
    hhuijser,\
    igorbeslic,\
    iovaneale,\
    ivicac,\
    javierdearcos,\
    jbalsas,\
    jeremy-ch,\
    john-co,\
    jonmak08,\
    joseabelenda,\
    joshchong,\
    joycewang08211,\
    jpince,\
    kenjiheigel,\
    kiyoshilee,\
    koor4356,\
    kyle-miho,\
    lanceji92674957,\
    liferay-continuous-integration,\
    liferay-continuous-integration-hu,\
    ling-alan-huang,\
    lionah,\
    liulukiwi,\
    liuxingye,\
    luca-pellizzon,\
    manoelcyreno,\
    marcellustavares,\
    marco-leo,\
    mhan810,\
    michaelhashimoto,\
    michaelprigge,\
    mtambara,\
    mwilliams2014,\
    ngriffin7a,\
    nhpatt,\
    palomaanunes,\
    patriciajeanperez,\
    pei-jung,\
    petershin,\
    preston-crary,\
    pyoo47,\
    rachaelkoestartyo,\
    riccardo-alberti,\
    riccardo-ferrari,\
    ruben-pulido,\
    ryanschuhler,\
    sharryxue,\
    shuyangzhou,\
    songyuewen,\
    stian-sigvartsen,\
    stmerriss,\
    suilin,\
    tim-cao,\
    timpak,\
    tinatian,\
    topolik,\
    vicnate5,\
    victorg1991,\
    wesleygong,\
    willnewbury,\
    wincent,\
    xbrianlee,\
    yichenroy,\
    yunlinsun

ci.test.available.suites=\
    acceptance,\
    acceptance-functional,\
    acceptance-upstream,\
    analytics-cloud,\
    backend,\
    blade,\
    blogs,\
    bundle,\
    clustering,\
    commerce,\
    commerce-es7,\
    commerce-es7-remote,\
    commerce-functional,\
    commerce-remote,\
    dl-store,\
    document,\
    environments,\
    gauntlet,\
    gauntlet-bucket,\
    gradle-plugins,\
    jdk11,\
    jsf,\
    knowledge-base,\
    ldap,\
    license,\
    license-cluster,\
    lpkg,\
    message-boards,\
    oauth,\
    poshi,\
    poshi-gauntlet,\
    relevant,\
    saml,\
    search,\
    search-es7,\
    search-es7-remote,\
    search-es7-remote-jdk11,\
    search-es7-remote-minimum,\
    search-remote,\
    search-remote-jdk11,\
    search-remote-minimum,\
    search-solr,\
    search-solr8,\
    security,\
    sf,\
    stable,\
    staging,\
    tango-analytics-cloud,\
    tck,\
    upgrade,\
    upgrade-client,\
    upstream-functional

ci.test.suite.description[acceptance]=Test acceptance tests.
ci.test.suite.description[acceptance-functional]=Test acceptance functional tests.
ci.test.suite.description[acceptance-upstream]=Test acceptance upstream tests.
ci.test.suite.description[blade]=Test only Blade samples tests.
ci.test.suite.description[bundle]=Saves a compiled tomcat bundle.
ci.test.suite.description[clustering]=Test only clustering.
ci.test.suite.description[commerce]=Test only Commerce tests.
ci.test.suite.description[commerce-es7]=Test only Commerce tests with the Elasticsearch 7 search engine.
ci.test.suite.description[commerce-es7-remote]=Test only Commerce tests with the latest compatible remote Elasticsearch 7 version.
ci.test.suite.description[commerce-functional]=Test only Commerce functional tests.
ci.test.suite.description[commerce-remote]=Test only Commerce tests with the latest compatible remote Elasticsearch 6 version.
ci.test.suite.description[dl-store]=Run Document Library Store tests.
ci.test.suite.description[environments]=Test environment acceptance functional tests on all available environment stacks.
ci.test.suite.description[gauntlet]=Test upstream tests.
ci.test.suite.description[gauntlet-bucket]=Test a subset of upstream tests.
ci.test.suite.description[gradle-plugins]=Test only Gradle Plugins tests.
ci.test.suite.description[jdk11]=Test acceptance, smoke, and upgrade functional tests against JDK11.
ci.test.suite.description[jsf]=Test only Liferay Faces tests.
ci.test.suite.description[ldap]=Test only LDAP tests.
ci.test.suite.description[license]=Compile a release bundle and execute tests for licensing.
ci.test.suite.description[license-cluster]=Compile a release bundle and execute tests for cluster licensing on 32GB slaves.
ci.test.suite.description[lpkg]=Test only LPKG tests.
ci.test.suite.description[oauth2]=Test only OAuth 2 tests.
ci.test.suite.description[relevant]=Test relevant changes only.
ci.test.suite.description[saml]=Test only SAML tests.
ci.test.suite.description[search]=Test only search tests with the Elasticsearch 6 search engine.
ci.test.suite.description[search-es7]=Test only search tests with the Elasticsearch 7 search engine.
ci.test.suite.description[search-es7-remote]=Test only search tests with the latest compatible remote Elasticsearch 7 version.
ci.test.suite.description[search-es7-remote-jdk11]=Test only search tests with the latest compatible remote Elasticsearch 7 version and OpenJDK 11.
ci.test.suite.description[search-es7-remote-minimum]=Test only search tests with the minimum compatible remote Elasticsearch 7 version.
ci.test.suite.description[search-remote]=Test only search tests with the latest compatible remote Elasticsearch 6 version.
ci.test.suite.description[search-remote-jdk11]=Test only search tests with the latest compatible remote Elasticsearch 6 version and OpenJDK 11.
ci.test.suite.description[search-remote-minimum]=Test only search tests with the minimum compatible remote Elasticsearch 6 version.
ci.test.suite.description[search-solr]=Test only search tests with the Solr 7 search engine.
ci.test.suite.description[search-solr8]=Test only search tests with the Solr 8 search engine.
ci.test.suite.description[security]=Test only security tests.
ci.test.suite.description[sf]=Test with only source formatter.
ci.test.suite.description[staging]=Test only staging tests.
ci.test.suite.description[tango-analytics-cloud]=Test segmentation and personalization with Analytics Cloud.
ci.test.suite.description[tck]=Test only TCK tests.
ci.test.suite.description[upgrade]=Test with all upgrade tests.
ci.test.suite.description[upgrade-client]=Test only upgrade client.
ci.test.suite.description[upstream-functional]=Test upstream functional tests.

jira.project.keys=\
    APIO,\
    ASAH,\
    BLADE,\
    CEREBRO,\
    CLDSVCS,\
    COMMERCE,\
    FARO,\
    IDE,\
    ISOPS,\
    ISSUP,\
    LOOP,\
    LPS,\
    LRAC,\
    LRCI,\
    LRDCOM,\
    LRDOCS,\
    LRIS,\
    LRQA,\
    OAUTH2,\
    POSHI,\
    RELEASE,\
    SYNC,\
    TR,\
    WCM