/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.commerce.data.integration.manager.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.commerce.data.integration.manager.model.History;
import com.liferay.commerce.data.integration.manager.model.HistoryModel;
import com.liferay.commerce.data.integration.manager.model.HistorySoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the History service. Represents a row in the &quot;History&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>HistoryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HistoryImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see HistoryImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class HistoryModelImpl
	extends BaseModelImpl<History> implements HistoryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a history model instance should use the <code>History</code> interface instead.
	 */
	public static final String TABLE_NAME = "History";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"historyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"launchType", Types.VARCHAR}, {"scheduledTaskId", Types.BIGINT},
		{"status", Types.INTEGER}, {"startDate", Types.TIMESTAMP},
		{"endDate", Types.TIMESTAMP}, {"executionType", Types.VARCHAR},
		{"errorLogFileEntryId", Types.BIGINT},
		{"runtimeLogFileEntryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("historyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("launchType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("scheduledTaskId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("executionType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("errorLogFileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("runtimeLogFileEntryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table History (uuid_ VARCHAR(75) null,historyId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,launchType VARCHAR(75) null,scheduledTaskId LONG,status INTEGER,startDate DATE null,endDate DATE null,executionType VARCHAR(75) null,errorLogFileEntryId LONG,runtimeLogFileEntryId LONG)";

	public static final String TABLE_SQL_DROP = "drop table History";

	public static final String ORDER_BY_JPQL =
		" ORDER BY history.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY History.modifiedDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.data.integration.manager.service.util.ServiceProps.
			get(
				"value.object.entity.cache.enabled.com.liferay.commerce.data.integration.manager.model.History"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.data.integration.manager.service.util.ServiceProps.
			get(
				"value.object.finder.cache.enabled.com.liferay.commerce.data.integration.manager.model.History"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.data.integration.manager.service.util.ServiceProps.
			get(
				"value.object.column.bitmask.enabled.com.liferay.commerce.data.integration.manager.model.History"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long SCHEDULEDTASKID_COLUMN_BITMASK = 4L;

	public static final long STATUS_COLUMN_BITMASK = 8L;

	public static final long UUID_COLUMN_BITMASK = 16L;

	public static final long MODIFIEDDATE_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static History toModel(HistorySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		History model = new HistoryImpl();

		model.setUuid(soapModel.getUuid());
		model.setHistoryId(soapModel.getHistoryId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setLaunchType(soapModel.getLaunchType());
		model.setScheduledTaskId(soapModel.getScheduledTaskId());
		model.setStatus(soapModel.getStatus());
		model.setStartDate(soapModel.getStartDate());
		model.setEndDate(soapModel.getEndDate());
		model.setExecutionType(soapModel.getExecutionType());
		model.setErrorLogFileEntryId(soapModel.getErrorLogFileEntryId());
		model.setRuntimeLogFileEntryId(soapModel.getRuntimeLogFileEntryId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<History> toModels(HistorySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<History> models = new ArrayList<History>(soapModels.length);

		for (HistorySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.commerce.data.integration.manager.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.commerce.data.integration.manager.model.History"));

	public HistoryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _historyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setHistoryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _historyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return History.class;
	}

	@Override
	public String getModelClassName() {
		return History.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<History, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<History, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<History, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((History)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<History, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<History, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(History)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<History, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<History, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, History>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			History.class.getClassLoader(), History.class, ModelWrapper.class);

		try {
			Constructor<History> constructor =
				(Constructor<History>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<History, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<History, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<History, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<History, Object>>();
		Map<String, BiConsumer<History, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<History, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<History, Object>() {

				@Override
				public Object apply(History history) {
					return history.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<History, Object>() {

				@Override
				public void accept(History history, Object uuid) {
					history.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"historyId",
			new Function<History, Object>() {

				@Override
				public Object apply(History history) {
					return history.getHistoryId();
				}

			});
		attributeSetterBiConsumers.put(
			"historyId",
			new BiConsumer<History, Object>() {

				@Override
				public void accept(History history, Object historyId) {
					history.setHistoryId((Long)historyId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<History, Object>() {

				@Override
				public Object apply(History history) {
					return history.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<History, Object>() {

				@Override
				public void accept(History history, Object groupId) {
					history.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<History, Object>() {

				@Override
				public Object apply(History history) {
					return history.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<History, Object>() {

				@Override
				public void accept(History history, Object companyId) {
					history.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<History, Object>() {

				@Override
				public Object apply(History history) {
					return history.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<History, Object>() {

				@Override
				public void accept(History history, Object userId) {
					history.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<History, Object>() {

				@Override
				public Object apply(History history) {
					return history.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<History, Object>() {

				@Override
				public void accept(History history, Object userName) {
					history.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<History, Object>() {

				@Override
				public Object apply(History history) {
					return history.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<History, Object>() {

				@Override
				public void accept(History history, Object createDate) {
					history.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<History, Object>() {

				@Override
				public Object apply(History history) {
					return history.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<History, Object>() {

				@Override
				public void accept(History history, Object modifiedDate) {
					history.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"launchType",
			new Function<History, Object>() {

				@Override
				public Object apply(History history) {
					return history.getLaunchType();
				}

			});
		attributeSetterBiConsumers.put(
			"launchType",
			new BiConsumer<History, Object>() {

				@Override
				public void accept(History history, Object launchType) {
					history.setLaunchType((String)launchType);
				}

			});
		attributeGetterFunctions.put(
			"scheduledTaskId",
			new Function<History, Object>() {

				@Override
				public Object apply(History history) {
					return history.getScheduledTaskId();
				}

			});
		attributeSetterBiConsumers.put(
			"scheduledTaskId",
			new BiConsumer<History, Object>() {

				@Override
				public void accept(History history, Object scheduledTaskId) {
					history.setScheduledTaskId((Long)scheduledTaskId);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<History, Object>() {

				@Override
				public Object apply(History history) {
					return history.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<History, Object>() {

				@Override
				public void accept(History history, Object status) {
					history.setStatus((Integer)status);
				}

			});
		attributeGetterFunctions.put(
			"startDate",
			new Function<History, Object>() {

				@Override
				public Object apply(History history) {
					return history.getStartDate();
				}

			});
		attributeSetterBiConsumers.put(
			"startDate",
			new BiConsumer<History, Object>() {

				@Override
				public void accept(History history, Object startDate) {
					history.setStartDate((Date)startDate);
				}

			});
		attributeGetterFunctions.put(
			"endDate",
			new Function<History, Object>() {

				@Override
				public Object apply(History history) {
					return history.getEndDate();
				}

			});
		attributeSetterBiConsumers.put(
			"endDate",
			new BiConsumer<History, Object>() {

				@Override
				public void accept(History history, Object endDate) {
					history.setEndDate((Date)endDate);
				}

			});
		attributeGetterFunctions.put(
			"executionType",
			new Function<History, Object>() {

				@Override
				public Object apply(History history) {
					return history.getExecutionType();
				}

			});
		attributeSetterBiConsumers.put(
			"executionType",
			new BiConsumer<History, Object>() {

				@Override
				public void accept(History history, Object executionType) {
					history.setExecutionType((String)executionType);
				}

			});
		attributeGetterFunctions.put(
			"errorLogFileEntryId",
			new Function<History, Object>() {

				@Override
				public Object apply(History history) {
					return history.getErrorLogFileEntryId();
				}

			});
		attributeSetterBiConsumers.put(
			"errorLogFileEntryId",
			new BiConsumer<History, Object>() {

				@Override
				public void accept(
					History history, Object errorLogFileEntryId) {

					history.setErrorLogFileEntryId((Long)errorLogFileEntryId);
				}

			});
		attributeGetterFunctions.put(
			"runtimeLogFileEntryId",
			new Function<History, Object>() {

				@Override
				public Object apply(History history) {
					return history.getRuntimeLogFileEntryId();
				}

			});
		attributeSetterBiConsumers.put(
			"runtimeLogFileEntryId",
			new BiConsumer<History, Object>() {

				@Override
				public void accept(
					History history, Object runtimeLogFileEntryId) {

					history.setRuntimeLogFileEntryId(
						(Long)runtimeLogFileEntryId);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getHistoryId() {
		return _historyId;
	}

	@Override
	public void setHistoryId(long historyId) {
		_historyId = historyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_columnBitmask = -1L;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getLaunchType() {
		if (_launchType == null) {
			return "";
		}
		else {
			return _launchType;
		}
	}

	@Override
	public void setLaunchType(String launchType) {
		_launchType = launchType;
	}

	@JSON
	@Override
	public long getScheduledTaskId() {
		return _scheduledTaskId;
	}

	@Override
	public void setScheduledTaskId(long scheduledTaskId) {
		_columnBitmask |= SCHEDULEDTASKID_COLUMN_BITMASK;

		if (!_setOriginalScheduledTaskId) {
			_setOriginalScheduledTaskId = true;

			_originalScheduledTaskId = _scheduledTaskId;
		}

		_scheduledTaskId = scheduledTaskId;
	}

	public long getOriginalScheduledTaskId() {
		return _originalScheduledTaskId;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		_endDate = endDate;
	}

	@JSON
	@Override
	public String getExecutionType() {
		if (_executionType == null) {
			return "";
		}
		else {
			return _executionType;
		}
	}

	@Override
	public void setExecutionType(String executionType) {
		_executionType = executionType;
	}

	@JSON
	@Override
	public long getErrorLogFileEntryId() {
		return _errorLogFileEntryId;
	}

	@Override
	public void setErrorLogFileEntryId(long errorLogFileEntryId) {
		_errorLogFileEntryId = errorLogFileEntryId;
	}

	@JSON
	@Override
	public long getRuntimeLogFileEntryId() {
		return _runtimeLogFileEntryId;
	}

	@Override
	public void setRuntimeLogFileEntryId(long runtimeLogFileEntryId) {
		_runtimeLogFileEntryId = runtimeLogFileEntryId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(History.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), History.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public History toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		HistoryImpl historyImpl = new HistoryImpl();

		historyImpl.setUuid(getUuid());
		historyImpl.setHistoryId(getHistoryId());
		historyImpl.setGroupId(getGroupId());
		historyImpl.setCompanyId(getCompanyId());
		historyImpl.setUserId(getUserId());
		historyImpl.setUserName(getUserName());
		historyImpl.setCreateDate(getCreateDate());
		historyImpl.setModifiedDate(getModifiedDate());
		historyImpl.setLaunchType(getLaunchType());
		historyImpl.setScheduledTaskId(getScheduledTaskId());
		historyImpl.setStatus(getStatus());
		historyImpl.setStartDate(getStartDate());
		historyImpl.setEndDate(getEndDate());
		historyImpl.setExecutionType(getExecutionType());
		historyImpl.setErrorLogFileEntryId(getErrorLogFileEntryId());
		historyImpl.setRuntimeLogFileEntryId(getRuntimeLogFileEntryId());

		historyImpl.resetOriginalValues();

		return historyImpl;
	}

	@Override
	public int compareTo(History history) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), history.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof History)) {
			return false;
		}

		History history = (History)obj;

		long primaryKey = history.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		HistoryModelImpl historyModelImpl = this;

		historyModelImpl._originalUuid = historyModelImpl._uuid;

		historyModelImpl._originalGroupId = historyModelImpl._groupId;

		historyModelImpl._setOriginalGroupId = false;

		historyModelImpl._originalCompanyId = historyModelImpl._companyId;

		historyModelImpl._setOriginalCompanyId = false;

		historyModelImpl._setModifiedDate = false;

		historyModelImpl._originalScheduledTaskId =
			historyModelImpl._scheduledTaskId;

		historyModelImpl._setOriginalScheduledTaskId = false;

		historyModelImpl._originalStatus = historyModelImpl._status;

		historyModelImpl._setOriginalStatus = false;

		historyModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<History> toCacheModel() {
		HistoryCacheModel historyCacheModel = new HistoryCacheModel();

		historyCacheModel.uuid = getUuid();

		String uuid = historyCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			historyCacheModel.uuid = null;
		}

		historyCacheModel.historyId = getHistoryId();

		historyCacheModel.groupId = getGroupId();

		historyCacheModel.companyId = getCompanyId();

		historyCacheModel.userId = getUserId();

		historyCacheModel.userName = getUserName();

		String userName = historyCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			historyCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			historyCacheModel.createDate = createDate.getTime();
		}
		else {
			historyCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			historyCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			historyCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		historyCacheModel.launchType = getLaunchType();

		String launchType = historyCacheModel.launchType;

		if ((launchType != null) && (launchType.length() == 0)) {
			historyCacheModel.launchType = null;
		}

		historyCacheModel.scheduledTaskId = getScheduledTaskId();

		historyCacheModel.status = getStatus();

		Date startDate = getStartDate();

		if (startDate != null) {
			historyCacheModel.startDate = startDate.getTime();
		}
		else {
			historyCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			historyCacheModel.endDate = endDate.getTime();
		}
		else {
			historyCacheModel.endDate = Long.MIN_VALUE;
		}

		historyCacheModel.executionType = getExecutionType();

		String executionType = historyCacheModel.executionType;

		if ((executionType != null) && (executionType.length() == 0)) {
			historyCacheModel.executionType = null;
		}

		historyCacheModel.errorLogFileEntryId = getErrorLogFileEntryId();

		historyCacheModel.runtimeLogFileEntryId = getRuntimeLogFileEntryId();

		return historyCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<History, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<History, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<History, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((History)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<History, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<History, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<History, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((History)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, History>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	private String _uuid;
	private String _originalUuid;
	private long _historyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _launchType;
	private long _scheduledTaskId;
	private long _originalScheduledTaskId;
	private boolean _setOriginalScheduledTaskId;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private Date _startDate;
	private Date _endDate;
	private String _executionType;
	private long _errorLogFileEntryId;
	private long _runtimeLogFileEntryId;
	private long _columnBitmask;
	private History _escapedModel;

}