/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.commerce.data.integration.manager.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.commerce.data.integration.manager.model.Process;
import com.liferay.commerce.data.integration.manager.model.ProcessModel;
import com.liferay.commerce.data.integration.manager.model.ProcessSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Process service. Represents a row in the &quot;Process&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>ProcessModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProcessImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see ProcessImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ProcessModelImpl
	extends BaseModelImpl<Process> implements ProcessModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a process model instance should use the <code>Process</code> interface instead.
	 */
	public static final String TABLE_NAME = "Process";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"processId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"version", Types.VARCHAR},
		{"className", Types.VARCHAR}, {"processType", Types.VARCHAR},
		{"contextPropertiesFileEntryId", Types.BIGINT},
		{"srcArchiveFileEntryId", Types.BIGINT},
		{"contextProperties", Types.CLOB}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("processId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("version", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("className", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("processType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contextPropertiesFileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("srcArchiveFileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("contextProperties", Types.CLOB);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Process (uuid_ VARCHAR(75) null,processId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,version VARCHAR(75) null,className VARCHAR(75) null,processType VARCHAR(75) null,contextPropertiesFileEntryId LONG,srcArchiveFileEntryId LONG,contextProperties TEXT null)";

	public static final String TABLE_SQL_DROP = "drop table Process";

	public static final String ORDER_BY_JPQL =
		" ORDER BY process.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Process.modifiedDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.data.integration.manager.service.util.ServiceProps.
			get(
				"value.object.entity.cache.enabled.com.liferay.commerce.data.integration.manager.model.Process"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.data.integration.manager.service.util.ServiceProps.
			get(
				"value.object.finder.cache.enabled.com.liferay.commerce.data.integration.manager.model.Process"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.data.integration.manager.service.util.ServiceProps.
			get(
				"value.object.column.bitmask.enabled.com.liferay.commerce.data.integration.manager.model.Process"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long NAME_COLUMN_BITMASK = 4L;

	public static final long PROCESSTYPE_COLUMN_BITMASK = 8L;

	public static final long UUID_COLUMN_BITMASK = 16L;

	public static final long MODIFIEDDATE_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Process toModel(ProcessSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Process model = new ProcessImpl();

		model.setUuid(soapModel.getUuid());
		model.setProcessId(soapModel.getProcessId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setVersion(soapModel.getVersion());
		model.setClassName(soapModel.getClassName());
		model.setProcessType(soapModel.getProcessType());
		model.setContextPropertiesFileEntryId(
			soapModel.getContextPropertiesFileEntryId());
		model.setSrcArchiveFileEntryId(soapModel.getSrcArchiveFileEntryId());
		model.setContextProperties(soapModel.getContextProperties());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Process> toModels(ProcessSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Process> models = new ArrayList<Process>(soapModels.length);

		for (ProcessSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.commerce.data.integration.manager.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.commerce.data.integration.manager.model.Process"));

	public ProcessModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _processId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProcessId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _processId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Process.class;
	}

	@Override
	public String getModelClassName() {
		return Process.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Process, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Process, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Process, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Process)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Process, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Process, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Process)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Process, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Process, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Process>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Process.class.getClassLoader(), Process.class, ModelWrapper.class);

		try {
			Constructor<Process> constructor =
				(Constructor<Process>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Process, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Process, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Process, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Process, Object>>();
		Map<String, BiConsumer<Process, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Process, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<Process, Object>() {

				@Override
				public Object apply(Process process) {
					return process.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<Process, Object>() {

				@Override
				public void accept(Process process, Object uuid) {
					process.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"processId",
			new Function<Process, Object>() {

				@Override
				public Object apply(Process process) {
					return process.getProcessId();
				}

			});
		attributeSetterBiConsumers.put(
			"processId",
			new BiConsumer<Process, Object>() {

				@Override
				public void accept(Process process, Object processId) {
					process.setProcessId((Long)processId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<Process, Object>() {

				@Override
				public Object apply(Process process) {
					return process.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<Process, Object>() {

				@Override
				public void accept(Process process, Object groupId) {
					process.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<Process, Object>() {

				@Override
				public Object apply(Process process) {
					return process.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<Process, Object>() {

				@Override
				public void accept(Process process, Object companyId) {
					process.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<Process, Object>() {

				@Override
				public Object apply(Process process) {
					return process.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<Process, Object>() {

				@Override
				public void accept(Process process, Object userId) {
					process.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<Process, Object>() {

				@Override
				public Object apply(Process process) {
					return process.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<Process, Object>() {

				@Override
				public void accept(Process process, Object userName) {
					process.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<Process, Object>() {

				@Override
				public Object apply(Process process) {
					return process.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<Process, Object>() {

				@Override
				public void accept(Process process, Object createDate) {
					process.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<Process, Object>() {

				@Override
				public Object apply(Process process) {
					return process.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<Process, Object>() {

				@Override
				public void accept(Process process, Object modifiedDate) {
					process.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<Process, Object>() {

				@Override
				public Object apply(Process process) {
					return process.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<Process, Object>() {

				@Override
				public void accept(Process process, Object name) {
					process.setName((String)name);
				}

			});
		attributeGetterFunctions.put(
			"version",
			new Function<Process, Object>() {

				@Override
				public Object apply(Process process) {
					return process.getVersion();
				}

			});
		attributeSetterBiConsumers.put(
			"version",
			new BiConsumer<Process, Object>() {

				@Override
				public void accept(Process process, Object version) {
					process.setVersion((String)version);
				}

			});
		attributeGetterFunctions.put(
			"className",
			new Function<Process, Object>() {

				@Override
				public Object apply(Process process) {
					return process.getClassName();
				}

			});
		attributeSetterBiConsumers.put(
			"className",
			new BiConsumer<Process, Object>() {

				@Override
				public void accept(Process process, Object className) {
					process.setClassName((String)className);
				}

			});
		attributeGetterFunctions.put(
			"processType",
			new Function<Process, Object>() {

				@Override
				public Object apply(Process process) {
					return process.getProcessType();
				}

			});
		attributeSetterBiConsumers.put(
			"processType",
			new BiConsumer<Process, Object>() {

				@Override
				public void accept(Process process, Object processType) {
					process.setProcessType((String)processType);
				}

			});
		attributeGetterFunctions.put(
			"contextPropertiesFileEntryId",
			new Function<Process, Object>() {

				@Override
				public Object apply(Process process) {
					return process.getContextPropertiesFileEntryId();
				}

			});
		attributeSetterBiConsumers.put(
			"contextPropertiesFileEntryId",
			new BiConsumer<Process, Object>() {

				@Override
				public void accept(
					Process process, Object contextPropertiesFileEntryId) {

					process.setContextPropertiesFileEntryId(
						(Long)contextPropertiesFileEntryId);
				}

			});
		attributeGetterFunctions.put(
			"srcArchiveFileEntryId",
			new Function<Process, Object>() {

				@Override
				public Object apply(Process process) {
					return process.getSrcArchiveFileEntryId();
				}

			});
		attributeSetterBiConsumers.put(
			"srcArchiveFileEntryId",
			new BiConsumer<Process, Object>() {

				@Override
				public void accept(
					Process process, Object srcArchiveFileEntryId) {

					process.setSrcArchiveFileEntryId(
						(Long)srcArchiveFileEntryId);
				}

			});
		attributeGetterFunctions.put(
			"contextProperties",
			new Function<Process, Object>() {

				@Override
				public Object apply(Process process) {
					return process.getContextProperties();
				}

			});
		attributeSetterBiConsumers.put(
			"contextProperties",
			new BiConsumer<Process, Object>() {

				@Override
				public void accept(Process process, Object contextProperties) {
					process.setContextProperties((String)contextProperties);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getProcessId() {
		return _processId;
	}

	@Override
	public void setProcessId(long processId) {
		_processId = processId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_columnBitmask = -1L;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getVersion() {
		if (_version == null) {
			return "";
		}
		else {
			return _version;
		}
	}

	@Override
	public void setVersion(String version) {
		_version = version;
	}

	@JSON
	@Override
	public String getClassName() {
		if (_className == null) {
			return "";
		}
		else {
			return _className;
		}
	}

	@Override
	public void setClassName(String className) {
		_className = className;
	}

	@JSON
	@Override
	public String getProcessType() {
		if (_processType == null) {
			return "";
		}
		else {
			return _processType;
		}
	}

	@Override
	public void setProcessType(String processType) {
		_columnBitmask |= PROCESSTYPE_COLUMN_BITMASK;

		if (_originalProcessType == null) {
			_originalProcessType = _processType;
		}

		_processType = processType;
	}

	public String getOriginalProcessType() {
		return GetterUtil.getString(_originalProcessType);
	}

	@JSON
	@Override
	public long getContextPropertiesFileEntryId() {
		return _contextPropertiesFileEntryId;
	}

	@Override
	public void setContextPropertiesFileEntryId(
		long contextPropertiesFileEntryId) {

		_contextPropertiesFileEntryId = contextPropertiesFileEntryId;
	}

	@JSON
	@Override
	public long getSrcArchiveFileEntryId() {
		return _srcArchiveFileEntryId;
	}

	@Override
	public void setSrcArchiveFileEntryId(long srcArchiveFileEntryId) {
		_srcArchiveFileEntryId = srcArchiveFileEntryId;
	}

	@JSON
	@Override
	public String getContextProperties() {
		if (_contextProperties == null) {
			return "";
		}
		else {
			return _contextProperties;
		}
	}

	@Override
	public void setContextProperties(String contextProperties) {
		_contextProperties = contextProperties;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Process.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Process.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Process toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProcessImpl processImpl = new ProcessImpl();

		processImpl.setUuid(getUuid());
		processImpl.setProcessId(getProcessId());
		processImpl.setGroupId(getGroupId());
		processImpl.setCompanyId(getCompanyId());
		processImpl.setUserId(getUserId());
		processImpl.setUserName(getUserName());
		processImpl.setCreateDate(getCreateDate());
		processImpl.setModifiedDate(getModifiedDate());
		processImpl.setName(getName());
		processImpl.setVersion(getVersion());
		processImpl.setClassName(getClassName());
		processImpl.setProcessType(getProcessType());
		processImpl.setContextPropertiesFileEntryId(
			getContextPropertiesFileEntryId());
		processImpl.setSrcArchiveFileEntryId(getSrcArchiveFileEntryId());
		processImpl.setContextProperties(getContextProperties());

		processImpl.resetOriginalValues();

		return processImpl;
	}

	@Override
	public int compareTo(Process process) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), process.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Process)) {
			return false;
		}

		Process process = (Process)obj;

		long primaryKey = process.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ProcessModelImpl processModelImpl = this;

		processModelImpl._originalUuid = processModelImpl._uuid;

		processModelImpl._originalGroupId = processModelImpl._groupId;

		processModelImpl._setOriginalGroupId = false;

		processModelImpl._originalCompanyId = processModelImpl._companyId;

		processModelImpl._setOriginalCompanyId = false;

		processModelImpl._setModifiedDate = false;

		processModelImpl._originalName = processModelImpl._name;

		processModelImpl._originalProcessType = processModelImpl._processType;

		processModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Process> toCacheModel() {
		ProcessCacheModel processCacheModel = new ProcessCacheModel();

		processCacheModel.uuid = getUuid();

		String uuid = processCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			processCacheModel.uuid = null;
		}

		processCacheModel.processId = getProcessId();

		processCacheModel.groupId = getGroupId();

		processCacheModel.companyId = getCompanyId();

		processCacheModel.userId = getUserId();

		processCacheModel.userName = getUserName();

		String userName = processCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			processCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			processCacheModel.createDate = createDate.getTime();
		}
		else {
			processCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			processCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			processCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		processCacheModel.name = getName();

		String name = processCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			processCacheModel.name = null;
		}

		processCacheModel.version = getVersion();

		String version = processCacheModel.version;

		if ((version != null) && (version.length() == 0)) {
			processCacheModel.version = null;
		}

		processCacheModel.className = getClassName();

		String className = processCacheModel.className;

		if ((className != null) && (className.length() == 0)) {
			processCacheModel.className = null;
		}

		processCacheModel.processType = getProcessType();

		String processType = processCacheModel.processType;

		if ((processType != null) && (processType.length() == 0)) {
			processCacheModel.processType = null;
		}

		processCacheModel.contextPropertiesFileEntryId =
			getContextPropertiesFileEntryId();

		processCacheModel.srcArchiveFileEntryId = getSrcArchiveFileEntryId();

		processCacheModel.contextProperties = getContextProperties();

		String contextProperties = processCacheModel.contextProperties;

		if ((contextProperties != null) && (contextProperties.length() == 0)) {
			processCacheModel.contextProperties = null;
		}

		return processCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Process, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Process, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Process, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Process)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Process, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Process, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Process, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Process)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, Process>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	private String _uuid;
	private String _originalUuid;
	private long _processId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private String _version;
	private String _className;
	private String _processType;
	private String _originalProcessType;
	private long _contextPropertiesFileEntryId;
	private long _srcArchiveFileEntryId;
	private String _contextProperties;
	private long _columnBitmask;
	private Process _escapedModel;

}