/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.commerce.data.integration.manager.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.commerce.data.integration.manager.model.ScheduledTask;
import com.liferay.commerce.data.integration.manager.model.ScheduledTaskModel;
import com.liferay.commerce.data.integration.manager.model.ScheduledTaskSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ScheduledTask service. Represents a row in the &quot;ScheduledTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>ScheduledTaskModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ScheduledTaskImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see ScheduledTaskImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ScheduledTaskModelImpl
	extends BaseModelImpl<ScheduledTask> implements ScheduledTaskModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a scheduled task model instance should use the <code>ScheduledTask</code> interface instead.
	 */
	public static final String TABLE_NAME = "ScheduledTask";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"scheduledTaskId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"frequency", Types.VARCHAR},
		{"processId", Types.BIGINT}, {"status", Types.INTEGER},
		{"active_", Types.BOOLEAN}, {"runStartDate", Types.TIMESTAMP},
		{"runEndDate", Types.TIMESTAMP}, {"startDate", Types.TIMESTAMP},
		{"startHour", Types.VARCHAR}, {"enabled", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("scheduledTaskId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("frequency", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("processId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("runStartDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("runEndDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("startHour", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("enabled", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ScheduledTask (uuid_ VARCHAR(75) null,scheduledTaskId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,frequency VARCHAR(75) null,processId LONG,status INTEGER,active_ BOOLEAN,runStartDate DATE null,runEndDate DATE null,startDate DATE null,startHour VARCHAR(75) null,enabled BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table ScheduledTask";

	public static final String ORDER_BY_JPQL =
		" ORDER BY scheduledTask.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ScheduledTask.modifiedDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.data.integration.manager.service.util.ServiceProps.
			get(
				"value.object.entity.cache.enabled.com.liferay.commerce.data.integration.manager.model.ScheduledTask"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.data.integration.manager.service.util.ServiceProps.
			get(
				"value.object.finder.cache.enabled.com.liferay.commerce.data.integration.manager.model.ScheduledTask"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.data.integration.manager.service.util.ServiceProps.
			get(
				"value.object.column.bitmask.enabled.com.liferay.commerce.data.integration.manager.model.ScheduledTask"),
		true);

	public static final long ACTIVE_COLUMN_BITMASK = 1L;

	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	public static final long ENABLED_COLUMN_BITMASK = 4L;

	public static final long GROUPID_COLUMN_BITMASK = 8L;

	public static final long NAME_COLUMN_BITMASK = 16L;

	public static final long UUID_COLUMN_BITMASK = 32L;

	public static final long MODIFIEDDATE_COLUMN_BITMASK = 64L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ScheduledTask toModel(ScheduledTaskSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ScheduledTask model = new ScheduledTaskImpl();

		model.setUuid(soapModel.getUuid());
		model.setScheduledTaskId(soapModel.getScheduledTaskId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setFrequency(soapModel.getFrequency());
		model.setProcessId(soapModel.getProcessId());
		model.setStatus(soapModel.getStatus());
		model.setActive(soapModel.isActive());
		model.setRunStartDate(soapModel.getRunStartDate());
		model.setRunEndDate(soapModel.getRunEndDate());
		model.setStartDate(soapModel.getStartDate());
		model.setStartHour(soapModel.getStartHour());
		model.setEnabled(soapModel.isEnabled());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ScheduledTask> toModels(ScheduledTaskSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ScheduledTask> models = new ArrayList<ScheduledTask>(
			soapModels.length);

		for (ScheduledTaskSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.commerce.data.integration.manager.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.commerce.data.integration.manager.model.ScheduledTask"));

	public ScheduledTaskModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _scheduledTaskId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setScheduledTaskId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _scheduledTaskId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ScheduledTask.class;
	}

	@Override
	public String getModelClassName() {
		return ScheduledTask.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ScheduledTask, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ScheduledTask, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ScheduledTask, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ScheduledTask)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ScheduledTask, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ScheduledTask, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ScheduledTask)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ScheduledTask, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ScheduledTask, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ScheduledTask>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ScheduledTask.class.getClassLoader(), ScheduledTask.class,
			ModelWrapper.class);

		try {
			Constructor<ScheduledTask> constructor =
				(Constructor<ScheduledTask>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<ScheduledTask, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ScheduledTask, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ScheduledTask, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ScheduledTask, Object>>();
		Map<String, BiConsumer<ScheduledTask, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ScheduledTask, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(ScheduledTask scheduledTask, Object uuid) {
					scheduledTask.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"scheduledTaskId",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getScheduledTaskId();
				}

			});
		attributeSetterBiConsumers.put(
			"scheduledTaskId",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(
					ScheduledTask scheduledTask, Object scheduledTaskId) {

					scheduledTask.setScheduledTaskId((Long)scheduledTaskId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(
					ScheduledTask scheduledTask, Object groupId) {

					scheduledTask.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(
					ScheduledTask scheduledTask, Object companyId) {

					scheduledTask.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(ScheduledTask scheduledTask, Object userId) {
					scheduledTask.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(
					ScheduledTask scheduledTask, Object userName) {

					scheduledTask.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(
					ScheduledTask scheduledTask, Object createDate) {

					scheduledTask.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(
					ScheduledTask scheduledTask, Object modifiedDate) {

					scheduledTask.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(ScheduledTask scheduledTask, Object name) {
					scheduledTask.setName((String)name);
				}

			});
		attributeGetterFunctions.put(
			"frequency",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getFrequency();
				}

			});
		attributeSetterBiConsumers.put(
			"frequency",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(
					ScheduledTask scheduledTask, Object frequency) {

					scheduledTask.setFrequency((String)frequency);
				}

			});
		attributeGetterFunctions.put(
			"processId",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getProcessId();
				}

			});
		attributeSetterBiConsumers.put(
			"processId",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(
					ScheduledTask scheduledTask, Object processId) {

					scheduledTask.setProcessId((Long)processId);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(ScheduledTask scheduledTask, Object status) {
					scheduledTask.setStatus((Integer)status);
				}

			});
		attributeGetterFunctions.put(
			"active",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getActive();
				}

			});
		attributeSetterBiConsumers.put(
			"active",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(ScheduledTask scheduledTask, Object active) {
					scheduledTask.setActive((Boolean)active);
				}

			});
		attributeGetterFunctions.put(
			"runStartDate",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getRunStartDate();
				}

			});
		attributeSetterBiConsumers.put(
			"runStartDate",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(
					ScheduledTask scheduledTask, Object runStartDate) {

					scheduledTask.setRunStartDate((Date)runStartDate);
				}

			});
		attributeGetterFunctions.put(
			"runEndDate",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getRunEndDate();
				}

			});
		attributeSetterBiConsumers.put(
			"runEndDate",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(
					ScheduledTask scheduledTask, Object runEndDate) {

					scheduledTask.setRunEndDate((Date)runEndDate);
				}

			});
		attributeGetterFunctions.put(
			"startDate",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getStartDate();
				}

			});
		attributeSetterBiConsumers.put(
			"startDate",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(
					ScheduledTask scheduledTask, Object startDate) {

					scheduledTask.setStartDate((Date)startDate);
				}

			});
		attributeGetterFunctions.put(
			"startHour",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getStartHour();
				}

			});
		attributeSetterBiConsumers.put(
			"startHour",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(
					ScheduledTask scheduledTask, Object startHour) {

					scheduledTask.setStartHour((String)startHour);
				}

			});
		attributeGetterFunctions.put(
			"enabled",
			new Function<ScheduledTask, Object>() {

				@Override
				public Object apply(ScheduledTask scheduledTask) {
					return scheduledTask.getEnabled();
				}

			});
		attributeSetterBiConsumers.put(
			"enabled",
			new BiConsumer<ScheduledTask, Object>() {

				@Override
				public void accept(
					ScheduledTask scheduledTask, Object enabled) {

					scheduledTask.setEnabled((Boolean)enabled);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getScheduledTaskId() {
		return _scheduledTaskId;
	}

	@Override
	public void setScheduledTaskId(long scheduledTaskId) {
		_scheduledTaskId = scheduledTaskId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_columnBitmask = -1L;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getFrequency() {
		if (_frequency == null) {
			return "";
		}
		else {
			return _frequency;
		}
	}

	@Override
	public void setFrequency(String frequency) {
		_frequency = frequency;
	}

	@JSON
	@Override
	public long getProcessId() {
		return _processId;
	}

	@Override
	public void setProcessId(long processId) {
		_processId = processId;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_columnBitmask |= ACTIVE_COLUMN_BITMASK;

		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	@JSON
	@Override
	public Date getRunStartDate() {
		return _runStartDate;
	}

	@Override
	public void setRunStartDate(Date runStartDate) {
		_runStartDate = runStartDate;
	}

	@JSON
	@Override
	public Date getRunEndDate() {
		return _runEndDate;
	}

	@Override
	public void setRunEndDate(Date runEndDate) {
		_runEndDate = runEndDate;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@JSON
	@Override
	public String getStartHour() {
		if (_startHour == null) {
			return "";
		}
		else {
			return _startHour;
		}
	}

	@Override
	public void setStartHour(String startHour) {
		_startHour = startHour;
	}

	@JSON
	@Override
	public boolean getEnabled() {
		return _enabled;
	}

	@JSON
	@Override
	public boolean isEnabled() {
		return _enabled;
	}

	@Override
	public void setEnabled(boolean enabled) {
		_columnBitmask |= ENABLED_COLUMN_BITMASK;

		if (!_setOriginalEnabled) {
			_setOriginalEnabled = true;

			_originalEnabled = _enabled;
		}

		_enabled = enabled;
	}

	public boolean getOriginalEnabled() {
		return _originalEnabled;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ScheduledTask.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ScheduledTask.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ScheduledTask toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ScheduledTaskImpl scheduledTaskImpl = new ScheduledTaskImpl();

		scheduledTaskImpl.setUuid(getUuid());
		scheduledTaskImpl.setScheduledTaskId(getScheduledTaskId());
		scheduledTaskImpl.setGroupId(getGroupId());
		scheduledTaskImpl.setCompanyId(getCompanyId());
		scheduledTaskImpl.setUserId(getUserId());
		scheduledTaskImpl.setUserName(getUserName());
		scheduledTaskImpl.setCreateDate(getCreateDate());
		scheduledTaskImpl.setModifiedDate(getModifiedDate());
		scheduledTaskImpl.setName(getName());
		scheduledTaskImpl.setFrequency(getFrequency());
		scheduledTaskImpl.setProcessId(getProcessId());
		scheduledTaskImpl.setStatus(getStatus());
		scheduledTaskImpl.setActive(isActive());
		scheduledTaskImpl.setRunStartDate(getRunStartDate());
		scheduledTaskImpl.setRunEndDate(getRunEndDate());
		scheduledTaskImpl.setStartDate(getStartDate());
		scheduledTaskImpl.setStartHour(getStartHour());
		scheduledTaskImpl.setEnabled(isEnabled());

		scheduledTaskImpl.resetOriginalValues();

		return scheduledTaskImpl;
	}

	@Override
	public int compareTo(ScheduledTask scheduledTask) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), scheduledTask.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ScheduledTask)) {
			return false;
		}

		ScheduledTask scheduledTask = (ScheduledTask)obj;

		long primaryKey = scheduledTask.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ScheduledTaskModelImpl scheduledTaskModelImpl = this;

		scheduledTaskModelImpl._originalUuid = scheduledTaskModelImpl._uuid;

		scheduledTaskModelImpl._originalGroupId =
			scheduledTaskModelImpl._groupId;

		scheduledTaskModelImpl._setOriginalGroupId = false;

		scheduledTaskModelImpl._originalCompanyId =
			scheduledTaskModelImpl._companyId;

		scheduledTaskModelImpl._setOriginalCompanyId = false;

		scheduledTaskModelImpl._setModifiedDate = false;

		scheduledTaskModelImpl._originalName = scheduledTaskModelImpl._name;

		scheduledTaskModelImpl._originalActive = scheduledTaskModelImpl._active;

		scheduledTaskModelImpl._setOriginalActive = false;

		scheduledTaskModelImpl._originalEnabled =
			scheduledTaskModelImpl._enabled;

		scheduledTaskModelImpl._setOriginalEnabled = false;

		scheduledTaskModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ScheduledTask> toCacheModel() {
		ScheduledTaskCacheModel scheduledTaskCacheModel =
			new ScheduledTaskCacheModel();

		scheduledTaskCacheModel.uuid = getUuid();

		String uuid = scheduledTaskCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			scheduledTaskCacheModel.uuid = null;
		}

		scheduledTaskCacheModel.scheduledTaskId = getScheduledTaskId();

		scheduledTaskCacheModel.groupId = getGroupId();

		scheduledTaskCacheModel.companyId = getCompanyId();

		scheduledTaskCacheModel.userId = getUserId();

		scheduledTaskCacheModel.userName = getUserName();

		String userName = scheduledTaskCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			scheduledTaskCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			scheduledTaskCacheModel.createDate = createDate.getTime();
		}
		else {
			scheduledTaskCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			scheduledTaskCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			scheduledTaskCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		scheduledTaskCacheModel.name = getName();

		String name = scheduledTaskCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			scheduledTaskCacheModel.name = null;
		}

		scheduledTaskCacheModel.frequency = getFrequency();

		String frequency = scheduledTaskCacheModel.frequency;

		if ((frequency != null) && (frequency.length() == 0)) {
			scheduledTaskCacheModel.frequency = null;
		}

		scheduledTaskCacheModel.processId = getProcessId();

		scheduledTaskCacheModel.status = getStatus();

		scheduledTaskCacheModel.active = isActive();

		Date runStartDate = getRunStartDate();

		if (runStartDate != null) {
			scheduledTaskCacheModel.runStartDate = runStartDate.getTime();
		}
		else {
			scheduledTaskCacheModel.runStartDate = Long.MIN_VALUE;
		}

		Date runEndDate = getRunEndDate();

		if (runEndDate != null) {
			scheduledTaskCacheModel.runEndDate = runEndDate.getTime();
		}
		else {
			scheduledTaskCacheModel.runEndDate = Long.MIN_VALUE;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			scheduledTaskCacheModel.startDate = startDate.getTime();
		}
		else {
			scheduledTaskCacheModel.startDate = Long.MIN_VALUE;
		}

		scheduledTaskCacheModel.startHour = getStartHour();

		String startHour = scheduledTaskCacheModel.startHour;

		if ((startHour != null) && (startHour.length() == 0)) {
			scheduledTaskCacheModel.startHour = null;
		}

		scheduledTaskCacheModel.enabled = isEnabled();

		return scheduledTaskCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ScheduledTask, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ScheduledTask, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ScheduledTask, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ScheduledTask)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ScheduledTask, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ScheduledTask, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ScheduledTask, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ScheduledTask)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, ScheduledTask>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	private String _uuid;
	private String _originalUuid;
	private long _scheduledTaskId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private String _frequency;
	private long _processId;
	private int _status;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private Date _runStartDate;
	private Date _runEndDate;
	private Date _startDate;
	private String _startHour;
	private boolean _enabled;
	private boolean _originalEnabled;
	private boolean _setOriginalEnabled;
	private long _columnBitmask;
	private ScheduledTask _escapedModel;

}