/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.faro.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.faro.model.FaroNotification;
import com.liferay.osb.faro.model.FaroNotificationModel;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FaroNotification service. Represents a row in the &quot;OSBFaro_FaroNotification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FaroNotificationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FaroNotificationImpl}.
 * </p>
 *
 * @author Matthew Kong
 * @see FaroNotificationImpl
 * @generated
 */
public class FaroNotificationModelImpl
	extends BaseModelImpl<FaroNotification> implements FaroNotificationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a faro notification model instance should use the <code>FaroNotification</code> interface instead.
	 */
	public static final String TABLE_NAME = "OSBFaro_FaroNotification";

	public static final Object[][] TABLE_COLUMNS = {
		{"faroNotificationId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"createTime", Types.BIGINT},
		{"modifiedTime", Types.BIGINT}, {"scope", Types.VARCHAR},
		{"read_", Types.BOOLEAN}, {"type_", Types.VARCHAR},
		{"subType", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("faroNotificationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("scope", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("read_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subType", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OSBFaro_FaroNotification (faroNotificationId LONG not null primary key,groupId LONG,userId LONG,createTime LONG,modifiedTime LONG,scope VARCHAR(75) null,read_ BOOLEAN,type_ VARCHAR(75) null,subType VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table OSBFaro_FaroNotification";

	public static final String ORDER_BY_JPQL =
		" ORDER BY faroNotification.faroNotificationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OSBFaro_FaroNotification.faroNotificationId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.faro.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.osb.faro.model.FaroNotification"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.faro.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.osb.faro.model.FaroNotification"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.osb.faro.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.osb.faro.model.FaroNotification"));

	public FaroNotificationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _faroNotificationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFaroNotificationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _faroNotificationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FaroNotification.class;
	}

	@Override
	public String getModelClassName() {
		return FaroNotification.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FaroNotification, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FaroNotification, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FaroNotification, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FaroNotification)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FaroNotification, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FaroNotification, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FaroNotification)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FaroNotification, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FaroNotification, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, FaroNotification>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			FaroNotification.class.getClassLoader(), FaroNotification.class,
			ModelWrapper.class);

		try {
			Constructor<FaroNotification> constructor =
				(Constructor<FaroNotification>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<FaroNotification, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<FaroNotification, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<FaroNotification, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<FaroNotification, Object>>();
		Map<String, BiConsumer<FaroNotification, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<FaroNotification, ?>>();

		attributeGetterFunctions.put(
			"faroNotificationId",
			new Function<FaroNotification, Object>() {

				@Override
				public Object apply(FaroNotification faroNotification) {
					return faroNotification.getFaroNotificationId();
				}

			});
		attributeSetterBiConsumers.put(
			"faroNotificationId",
			new BiConsumer<FaroNotification, Object>() {

				@Override
				public void accept(
					FaroNotification faroNotification,
					Object faroNotificationIdObject) {

					faroNotification.setFaroNotificationId(
						(Long)faroNotificationIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<FaroNotification, Object>() {

				@Override
				public Object apply(FaroNotification faroNotification) {
					return faroNotification.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<FaroNotification, Object>() {

				@Override
				public void accept(
					FaroNotification faroNotification, Object groupIdObject) {

					faroNotification.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<FaroNotification, Object>() {

				@Override
				public Object apply(FaroNotification faroNotification) {
					return faroNotification.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<FaroNotification, Object>() {

				@Override
				public void accept(
					FaroNotification faroNotification, Object userIdObject) {

					faroNotification.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"createTime",
			new Function<FaroNotification, Object>() {

				@Override
				public Object apply(FaroNotification faroNotification) {
					return faroNotification.getCreateTime();
				}

			});
		attributeSetterBiConsumers.put(
			"createTime",
			new BiConsumer<FaroNotification, Object>() {

				@Override
				public void accept(
					FaroNotification faroNotification,
					Object createTimeObject) {

					faroNotification.setCreateTime((Long)createTimeObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedTime",
			new Function<FaroNotification, Object>() {

				@Override
				public Object apply(FaroNotification faroNotification) {
					return faroNotification.getModifiedTime();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedTime",
			new BiConsumer<FaroNotification, Object>() {

				@Override
				public void accept(
					FaroNotification faroNotification,
					Object modifiedTimeObject) {

					faroNotification.setModifiedTime((Long)modifiedTimeObject);
				}

			});
		attributeGetterFunctions.put(
			"scope",
			new Function<FaroNotification, Object>() {

				@Override
				public Object apply(FaroNotification faroNotification) {
					return faroNotification.getScope();
				}

			});
		attributeSetterBiConsumers.put(
			"scope",
			new BiConsumer<FaroNotification, Object>() {

				@Override
				public void accept(
					FaroNotification faroNotification, Object scopeObject) {

					faroNotification.setScope((String)scopeObject);
				}

			});
		attributeGetterFunctions.put(
			"read",
			new Function<FaroNotification, Object>() {

				@Override
				public Object apply(FaroNotification faroNotification) {
					return faroNotification.getRead();
				}

			});
		attributeSetterBiConsumers.put(
			"read",
			new BiConsumer<FaroNotification, Object>() {

				@Override
				public void accept(
					FaroNotification faroNotification, Object readObject) {

					faroNotification.setRead((Boolean)readObject);
				}

			});
		attributeGetterFunctions.put(
			"type",
			new Function<FaroNotification, Object>() {

				@Override
				public Object apply(FaroNotification faroNotification) {
					return faroNotification.getType();
				}

			});
		attributeSetterBiConsumers.put(
			"type",
			new BiConsumer<FaroNotification, Object>() {

				@Override
				public void accept(
					FaroNotification faroNotification, Object typeObject) {

					faroNotification.setType((String)typeObject);
				}

			});
		attributeGetterFunctions.put(
			"subType",
			new Function<FaroNotification, Object>() {

				@Override
				public Object apply(FaroNotification faroNotification) {
					return faroNotification.getSubType();
				}

			});
		attributeSetterBiConsumers.put(
			"subType",
			new BiConsumer<FaroNotification, Object>() {

				@Override
				public void accept(
					FaroNotification faroNotification, Object subTypeObject) {

					faroNotification.setSubType((String)subTypeObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getFaroNotificationId() {
		return _faroNotificationId;
	}

	@Override
	public void setFaroNotificationId(long faroNotificationId) {
		_faroNotificationId = faroNotificationId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public long getCreateTime() {
		return _createTime;
	}

	@Override
	public void setCreateTime(long createTime) {
		_createTime = createTime;
	}

	@Override
	public long getModifiedTime() {
		return _modifiedTime;
	}

	@Override
	public void setModifiedTime(long modifiedTime) {
		_modifiedTime = modifiedTime;
	}

	@Override
	public String getScope() {
		if (_scope == null) {
			return "";
		}
		else {
			return _scope;
		}
	}

	@Override
	public void setScope(String scope) {
		_scope = scope;
	}

	@Override
	public boolean getRead() {
		return _read;
	}

	@Override
	public boolean isRead() {
		return _read;
	}

	@Override
	public void setRead(boolean read) {
		_read = read;
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_type = type;
	}

	@Override
	public String getSubType() {
		if (_subType == null) {
			return "";
		}
		else {
			return _subType;
		}
	}

	@Override
	public void setSubType(String subType) {
		_subType = subType;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, FaroNotification.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FaroNotification toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FaroNotification>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FaroNotificationImpl faroNotificationImpl = new FaroNotificationImpl();

		faroNotificationImpl.setFaroNotificationId(getFaroNotificationId());
		faroNotificationImpl.setGroupId(getGroupId());
		faroNotificationImpl.setUserId(getUserId());
		faroNotificationImpl.setCreateTime(getCreateTime());
		faroNotificationImpl.setModifiedTime(getModifiedTime());
		faroNotificationImpl.setScope(getScope());
		faroNotificationImpl.setRead(isRead());
		faroNotificationImpl.setType(getType());
		faroNotificationImpl.setSubType(getSubType());

		faroNotificationImpl.resetOriginalValues();

		return faroNotificationImpl;
	}

	@Override
	public int compareTo(FaroNotification faroNotification) {
		long primaryKey = faroNotification.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FaroNotification)) {
			return false;
		}

		FaroNotification faroNotification = (FaroNotification)object;

		long primaryKey = faroNotification.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<FaroNotification> toCacheModel() {
		FaroNotificationCacheModel faroNotificationCacheModel =
			new FaroNotificationCacheModel();

		faroNotificationCacheModel.faroNotificationId = getFaroNotificationId();

		faroNotificationCacheModel.groupId = getGroupId();

		faroNotificationCacheModel.userId = getUserId();

		faroNotificationCacheModel.createTime = getCreateTime();

		faroNotificationCacheModel.modifiedTime = getModifiedTime();

		faroNotificationCacheModel.scope = getScope();

		String scope = faroNotificationCacheModel.scope;

		if ((scope != null) && (scope.length() == 0)) {
			faroNotificationCacheModel.scope = null;
		}

		faroNotificationCacheModel.read = isRead();

		faroNotificationCacheModel.type = getType();

		String type = faroNotificationCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			faroNotificationCacheModel.type = null;
		}

		faroNotificationCacheModel.subType = getSubType();

		String subType = faroNotificationCacheModel.subType;

		if ((subType != null) && (subType.length() == 0)) {
			faroNotificationCacheModel.subType = null;
		}

		return faroNotificationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FaroNotification, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FaroNotification, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FaroNotification, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((FaroNotification)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<FaroNotification, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<FaroNotification, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FaroNotification, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((FaroNotification)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FaroNotification>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _faroNotificationId;
	private long _groupId;
	private long _userId;
	private long _createTime;
	private long _modifiedTime;
	private String _scope;
	private boolean _read;
	private String _type;
	private String _subType;
	private FaroNotification _escapedModel;

}