/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.faro.model.impl;

import com.liferay.osb.faro.model.FaroProjectEmailAddressDomain;
import com.liferay.osb.faro.service.FaroProjectEmailAddressDomainLocalServiceUtil;

/**
 * The extended model base implementation for the FaroProjectEmailAddressDomain service. Represents a row in the &quot;OSBFaro_FaroProjectEmailAddressDomain&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FaroProjectEmailAddressDomainImpl}.
 * </p>
 *
 * @author Matthew Kong
 * @see FaroProjectEmailAddressDomainImpl
 * @see FaroProjectEmailAddressDomain
 * @generated
 */
public abstract class FaroProjectEmailAddressDomainBaseImpl
	extends FaroProjectEmailAddressDomainModelImpl
	implements FaroProjectEmailAddressDomain {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a faro project email address domain model instance should use the <code>FaroProjectEmailAddressDomain</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FaroProjectEmailAddressDomainLocalServiceUtil.
				addFaroProjectEmailAddressDomain(this);
		}
		else {
			FaroProjectEmailAddressDomainLocalServiceUtil.
				updateFaroProjectEmailAddressDomain(this);
		}
	}

}