components:
    parameters:
        cartId:
            in: path
            explode: false
            name: cartId
            required: true
            schema:
                description:
                    Cart Id
                example: 30130
                format: int64
                minimum: 0
                type: integer
            style: simple
        channelId:
            in: path
            explode: false
            name: channelId
            required: true
            schema:
                description:
                    Channel Id
                example: 30130
                format: int64
                minimum: 0
                type: integer
            style: simple
    schemas:
        Cart:
            properties:
                accountId:
                    format: int64
                    readOnly: true
                    type: integer
                id:
                    format: int64
                    readOnly: true
                    type: integer
                orderItems:
                    items:
                        $ref: "#/components/schemas/OrderItem"
                    type: array
                summary:
                    $ref: "#/components/schemas/Summary"
            type: object
        Error:
            properties:
                errorCode:
                    description:
                        Internal error code mapping
                    example: 996
                    readOnly: true
                    type: integer
                errorDescription:
                    example: Unable to find currency. Currency code should be expressed with
                        3-letter ISO 4217 format.
                    readOnly: true
                    type: string
                message:
                    example: No CommerceCurrency exists with the key {groupId=41811, code=US
                        Dollar}
                    readOnly: true
                    type: string
                status:
                    description:
                        HTTP Status code
                    example: 404
                    readOnly: true
                    type: integer
            required:
                - errorCode
                - errorDescription
                - message
                - status
            type: object
        OrderItem:
            properties:
                id:
                    example: 30130
                    format: int64
                    minimum: 0
                    readOnly: true
                    type: integer
                name:
                    type: string
                quantity:
                    example: 30080
                    format: int32
                    minimum: 0
                    type: integer
            type: object
        Summary:
            properties:
                discount:
                    type: string
                itemsQuantity:
                    type: integer
                subTotal:
                    type: string
                total:
                    type: string
            type: object
info:
    description:
        Headless Delivery Commerce Cart API
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    title: Headless Delivery
    version: v1.0
openapi: 3.0.1
paths:
    /channels/{channelId}/carts/{cartId}:
        get:
            description:
                Retrive information of the given Cart.
            operationId: getChannelCart
            parameters:
                - in: path
                  explode: false
                  name: cartId
                  required: true
                  schema:
                      description:
                          Cart Id
                      example: 30130
                      format: int64
                      minimum: 0
                      type: integer
                  style: simple
                - in: path
                  explode: false
                  name: channelId
                  required: true
                  schema:
                      description:
                          Channel Id
                      example: 30130
                      format: int64
                      minimum: 0
                      type: integer
                  style: simple
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Cart"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Cart"
                401:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        Authentication information is missing or invalid
                404:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        The specified resource was not found
                500:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        Unexpected error
            tags: ["Cart"]
    /channels/{channelId}/carts:
        get:
            description:
                Retrieves carts for specific account in the given channl.
            operationId: getChannelCartsPage
            parameters:
                - in: path
                  explode: false
                  name: channelId
                  required: true
                  schema:
                      description:
                          Channel Id
                      example: 30130
                      format: int64
                      minimum: 0
                      type: integer
                  style: simple
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Cart"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Cart"
                                type: array
                    description:
                        Successful operation
                401:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        Authentication information is missing or invalid
                404:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        The specified resource was not found
                500:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    description:
                        Unexpected error
            tags: ["Cart"]
servers:
    - url: /