dependencies {
	testIntegrationCompile group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.8"
	testIntegrationCompile group: "com.liferay", name: "com.liferay.portal.rules.engine.api", version: "3.0.0"
	testIntegrationCompile group: "com.liferay", name: "com.liferay.registry.api", version: "2.0.0"
	testIntegrationCompile group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	testIntegrationCompile project(":private:apps:portal-rules-engine-drools:portal-rules-engine-drools-impl")
}