INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/calculator', 12345, 1, timestamp '${today-7h}', 'pageViewed', '1', '', 'session1', 'Try Our Online Calculator', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/binary', 12345, 1, timestamp '${today-6h}', 'pageViewed', '2', '', 'session1', 'How Binary Encoding is Used in a Computer', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-5h}', 'pageViewed', '3', '', 'session1', 'From Abacus to Modern Day Computers', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/calculator', 12345, 1, timestamp '${today-4h}', 'pageViewed', '4', '', 'session1', 'Try Our Online Calculator', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/binary', 12345, 1, timestamp '${today-3h}', 'pageViewed', '5', '', 'session1', 'How Binary Encoding is Used in a Computer', 'identity1');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/encoding', 12345, 1, timestamp '${today-17h}', 'pageViewed', '6', '', 'session2', 'How Do Computers Talk?', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/binary', 12345, 1, timestamp '${today-16h}', 'pageViewed', '7', '', 'session2', 'How Binary Encoding is Used in a Computer', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-15h}', 'pageViewed', '8', '', 'session2', 'From Abacus to Modern Day Computers', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/decimal', 12345, 1, timestamp '${today-14h}', 'pageViewed', '9', '', 'session2', 'Encoding Decimal to Binary', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/binary', 12345, 1, timestamp '${today-13h}', 'pageViewed', '10', '', 'session2', 'How Binary Encoding is Used in a Computer', 'identity1');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/calculator', 12345, 1, timestamp '${today-16h}', 'pageViewed', '11', '', 'session3', 'Are Calculators Computers?', 'identity2');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-15h}', 'pageViewed', '12', '', 'session3', 'From Abacus to Modern Day Computers', 'identity2');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/decimal', 12345, 1, timestamp '${today-14h}', 'pageViewed', '13', '', 'session3', 'Encoding Decimal to Binary', 'identity2');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/decimal', 12345, 1, timestamp '${today-12h}', 'pageViewed', '14', '', 'session4', 'Encoding Decimal to Binary', 'identity3');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-10h}', 'pageViewed', '15', '', 'session4', 'From Abacus to Modern Day Computers', 'identity3');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/encoding', 12345, 1, timestamp '${today-6h}', 'pageViewed', '16', '', 'session4', 'How Do Computers Talk?', 'identity3');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/encoding', 12345, 1, timestamp '${today-23h}', 'pageViewed', '17', '', 'session5', 'How Do Computers Talk?', 'identity4');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-22h}', 'pageViewed', '18', '', 'session5', 'From Abacus to Modern Day Computers', 'identity4');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/binary', 12345, 1, timestamp '${today-21h}', 'pageViewed', '19', '', 'session5', 'How Binary Encoding is Used in a Computer', 'identity4');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/gui', 12345, 1, timestamp '${today-23h}', 'pageViewed', '20', '', 'session6', 'Graphical User Interface', 'identity5');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-22h}', 'pageViewed', '21', '', 'session6', 'From Abacus to Modern Day Computers', 'identity5');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/files', 12345, 1, timestamp '${today-21h}', 'pageViewed', '22', '', 'session6', 'Computer File Systems', 'identity5');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/files', 12345, 1, timestamp '${today-23h}', 'pageViewed', '23', '', 'session7', 'Computer File Systems', 'identity6');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-22h}', 'pageViewed', '24', '', 'session7', 'From Abacus to Modern Day Computers', 'identity6');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/gui', 12345, 1, timestamp '${today-21h}', 'pageViewed', '25', '', 'session7', 'Graphical User Interface', 'identity6');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-22h}', 'pageViewed', '26', '', 'session8', 'From Abacus to Modern Day Computers', 'identity7');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-22h}', 'pageViewed', '27', '', 'session9', 'From Abacus to Modern Day Computers', 'identity8');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-22h}', 'pageViewed', '28', '', 'session10', 'From Abacus to Modern Day Computers', 'identity9');