INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '2023-10-22T00:03:00.000Z', 'pageViewed', '3', '', 'session1', 'From Abacus to Modern Day Computers', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/calculator', 12345, 1, timestamp '2023-10-22T04:00:00.000Z', 'pageViewed', '4', '', 'session1', 'Try Our Online Calculator', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/binary', 12345, 1, timestamp '2023-10-22T05:00:00.000Z', 'pageViewed', '5', '', 'session1', 'How Binary Encoding is Used in a Computer', 'identity1');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '2023-10-24T12:00:00.000Z', 'pageViewed', '8', '', 'session2', 'From Abacus to Modern Day Computers', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/decimal', 12345, 1, timestamp '2023-10-24T13:00:00.000Z', 'pageViewed', '9', '', 'session2', 'Encoding Decimal to Binary', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/binary', 12345, 1, timestamp '2023-10-24T14:00:00.000Z', 'pageViewed', '10', '', 'session2', 'How Binary Encoding is Used in a Computer', 'identity1');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '2023-10-26T22:00:00.000Z', 'pageViewed', '12', '', 'session3', 'From Abacus to Modern Day Computers', 'identity2');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/decimal', 12345, 1, timestamp '2023-10-26T23:00:00.000Z', 'pageViewed', '13', '', 'session3', 'Encoding Decimal to Binary', 'identity2');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '2023-10-28T07:00:00.000Z', 'pageViewed', '15', '', 'session4', 'From Abacus to Modern Day Computers', 'identity3');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/encoding', 12345, 1, timestamp '2023-10-28T11:00:00.000Z', 'pageViewed', '16', '', 'session4', 'How Do Computers Talk?', 'identity3');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '2023-10-30T05:00:00.000Z', 'pageViewed', '18', '', 'session5', 'From Abacus to Modern Day Computers', 'identity4');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/binary', 12345, 1, timestamp '2023-10-30T09:00:00.000Z', 'pageViewed', '19', '', 'session5', 'How Binary Encoding is Used in a Computer', 'identity4');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '2023-11-01T10:00:00.000Z', 'pageViewed', '21', '', 'session6', 'From Abacus to Modern Day Computers', 'identity5');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/files', 12345, 1, timestamp '2023-11-01T11:00:00.000Z', 'pageViewed', '22', '', 'session6', 'Computer File Systems', 'identity5');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '2023-11-03T12:00:00.000Z', 'pageViewed', '24', '', 'session7', 'From Abacus to Modern Day Computers', 'identity6');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/gui', 12345, 1, timestamp '2023-11-03T18:00:00.000Z', 'pageViewed', '25', '', 'session7', 'Graphical User Interface', 'identity6');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '2023-11-05T00:00:00.000Z', 'pageViewed', '26', '', 'session8', 'From Abacus to Modern Day Computers', 'identity7');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '2023-11-07T00:00:00.000Z', 'pageViewed', '27', '', 'session9', 'From Abacus to Modern Day Computers', 'identity8');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '2023-11-09T00:00:00.000Z', 'pageViewed', '28', '', 'session10', 'From Abacus to Modern Day Computers', 'identity9');