INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/calculator', 12345, 1, timestamp '${today-1dT01:00:00.000Z}', 'pageViewed', '1', '', 'session1', 'Try Our Online Calculator', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/binary', 12345, 1, timestamp '${today-1dT00:02:00.000Z}', 'pageViewed', '2', '', 'session1', 'How Binary Encoding is Used in a Computer', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-1dT00:03:00.000Z}', 'pageViewed', '3', '', 'session1', 'From Abacus to Modern Day Computers', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/calculator', 12345, 1, timestamp '${today-1dT04:00:00.000Z}', 'pageViewed', '4', '', 'session1', 'Try Our Online Calculator', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/binary', 12345, 1, timestamp '${today-1dT05:00:00.000Z}', 'pageViewed', '5', '', 'session1', 'How Binary Encoding is Used in a Computer', 'identity1');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/encoding', 12345, 1, timestamp '${today-2dT02:00:00.000Z}', 'pageViewed', '6', '', 'session2', 'How Do Computers Talk?', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/binary', 12345, 1, timestamp '${today-2dT03:00:00.000Z}', 'pageViewed', '7', '', 'session2', 'How Binary Encoding is Used in a Computer', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-2dT04:00:00.000Z}', 'pageViewed', '8', '', 'session2', 'From Abacus to Modern Day Computers', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/decimal', 12345, 1, timestamp '${today-2dT05:00:00.000Z}', 'pageViewed', '9', '', 'session2', 'Encoding Decimal to Binary', 'identity1');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/binary', 12345, 1, timestamp '${today-2dT06:00:00.000Z}', 'pageViewed', '10', '', 'session2', 'How Binary Encoding is Used in a Computer', 'identity1');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/calculator', 12345, 1, timestamp '${today-3dT04:00:00.000Z}', 'pageViewed', '11', '', 'session3', 'Are Calculators Computers?', 'identity2');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-3dT05:00:00.000Z}', 'pageViewed', '12', '', 'session3', 'From Abacus to Modern Day Computers', 'identity2');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/decimal', 12345, 1, timestamp '${today-3dT06:00:00.000Z}', 'pageViewed', '13', '', 'session3', 'Encoding Decimal to Binary', 'identity2');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/decimal', 12345, 1, timestamp '${today-3dT10:00:00.000Z}', 'pageViewed', '14', '', 'session4', 'Encoding Decimal to Binary', 'identity3');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-3dT11:00:00.000Z}', 'pageViewed', '15', '', 'session4', 'From Abacus to Modern Day Computers', 'identity3');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/encoding', 12345, 1, timestamp '${today-3dT12:00:00.000Z}', 'pageViewed', '16', '', 'session4', 'How Do Computers Talk?', 'identity3');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/encoding', 12345, 1, timestamp '${today-3dT13:00:00.000Z}', 'pageViewed', '17', '', 'session5', 'How Do Computers Talk?', 'identity4');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-3dT14:00:00.000Z}', 'pageViewed', '18', '', 'session5', 'From Abacus to Modern Day Computers', 'identity4');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/binary', 12345, 1, timestamp '${today-3dT15:00:00.000Z}', 'pageViewed', '19', '', 'session5', 'How Binary Encoding is Used in a Computer', 'identity4');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/gui', 12345, 1, timestamp '${today-4dT01:00:00.000Z}', 'pageViewed', '20', '', 'session6', 'Graphical User Interface', 'identity5');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-4dT02:00:00.000Z}', 'pageViewed', '21', '', 'session6', 'From Abacus to Modern Day Computers', 'identity5');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/files', 12345, 1, timestamp '${today-4dT03:00:00.000Z}', 'pageViewed', '22', '', 'session6', 'Computer File Systems', 'identity5');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/files', 12345, 1, timestamp '${today-5dT04:00:00.000Z}', 'pageViewed', '23', '', 'session7', 'Computer File Systems', 'identity6');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-5dT06:00:00.000Z}', 'pageViewed', '24', '', 'session7', 'From Abacus to Modern Day Computers', 'identity6');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/gui', 12345, 1, timestamp '${today-5dT07:00:00.000Z}', 'pageViewed', '25', '', 'session7', 'Graphical User Interface', 'identity6');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-5dT00:00:00.000Z}', 'pageViewed', '26', '', 'session8', 'From Abacus to Modern Day Computers', 'identity7');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-5dT00:00:00.000Z}', 'pageViewed', '27', '', 'session9', 'From Abacus to Modern Day Computers', 'identity8');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-5dT00:00:00.000Z}', 'pageViewed', '28', '', 'session10', 'From Abacus to Modern Day Computers', 'identity9');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/calculator', 12345, 1, timestamp '${today-27dT13:00:00.000Z}', 'pageViewed', '11', '', 'session11', 'Are Calculators Computers?', 'identity2');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-27dT15:00:00.000Z}', 'pageViewed', '12', '', 'session11', 'From Abacus to Modern Day Computers', 'identity2');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/decimal', 12345, 1, timestamp '${today-27dT19:00:00.000Z}', 'pageViewed', '13', '', 'session11', 'Encoding Decimal to Binary', 'identity2');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/decimal', 12345, 1, timestamp '${today-29dT11:00:00.000Z}', 'pageViewed', '14', '', 'session12', 'Encoding Decimal to Binary', 'identity3');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-29dT12:00:00.000Z}', 'pageViewed', '15', '', 'session12', 'From Abacus to Modern Day Computers', 'identity3');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/encoding', 12345, 1, timestamp '${today-29dT14:00:00.000Z}', 'pageViewed', '16', '', 'session12', 'How Do Computers Talk?', 'identity3');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/encoding', 12345, 1, timestamp '${today-31dT10:00:00.000Z}', 'pageViewed', '17', '', 'session13', 'How Do Computers Talk?', 'identity4');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-31dT20:00:00.000Z}', 'pageViewed', '18', '', 'session13', 'From Abacus to Modern Day Computers', 'identity4');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/binary', 12345, 1, timestamp '${today-31dT22:00:00.000Z}', 'pageViewed', '19', '', 'session13', 'How Binary Encoding is Used in a Computer', 'identity4');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/gui', 12345, 1, timestamp '${today-89dT07:00:00.000Z}', 'pageViewed', '20', '', 'session14', 'Graphical User Interface', 'identity5');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-89dT09:00:00.000Z}', 'pageViewed', '21', '', 'session14', 'From Abacus to Modern Day Computers', 'identity5');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/files', 12345, 1, timestamp '${today-89dT11:00:00.000Z}', 'pageViewed', '22', '', 'session14', 'Computer File Systems', 'identity5');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/files', 12345, 1, timestamp '${today-91dT01:00:00.000Z}', 'pageViewed', '23', '', 'session15', 'Computer File Systems', 'identity6');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-91dT02:00:00.000Z}', 'pageViewed', '24', '', 'session15', 'From Abacus to Modern Day Computers', 'identity6');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/gui', 12345, 1, timestamp '${today-91dT03:00:00.000Z}', 'pageViewed', '25', '', 'session15', 'Graphical User Interface', 'identity6');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/files', 12345, 1, timestamp '${today-179dT08:00:00.000Z}', 'pageViewed', '23', '', 'session16', 'Computer File Systems', 'identity6');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-179dT10:00:00.000Z}', 'pageViewed', '24', '', 'session16', 'From Abacus to Modern Day Computers', 'identity6');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/gui', 12345, 1, timestamp '${today-179dT17:00:00.000Z}', 'pageViewed', '25', '', 'session16', 'Graphical User Interface', 'identity6');

INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/files', 12345, 1, timestamp '${today-181dT04:00:00.000Z}', 'pageViewed', '23', '', 'session17', 'Computer File Systems', 'identity6');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/abacus', 12345, 1, timestamp '${today-181dT05:00:00.000Z}', 'pageViewed', '24', '', 'session17', 'From Abacus to Modern Day Computers', 'identity6');
INSERT INTO Event (applicationId, canonicalUrl, channelId, dataSourceId, eventDate, eventId, id, referrer, sessionId, title, userId) VALUES ('Page', 'https://www.computer.com/gui', 12345, 1, timestamp '${today-181dT10:00:00.000Z}', 'pageViewed', '25', '', 'session17', 'Graphical User Interface', 'identity6');