/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.asah.backend.rest.controller.api.data.source.v1.test;

import com.fasterxml.jackson.databind.ObjectMapper;

import com.liferay.osb.asah.backend.dto.PageDTO;
import com.liferay.osb.asah.backend.dto.SegmentDTO;
import com.liferay.osb.asah.backend.rest.controller.api.data.source.v1.IndividualSegmentsRestController;
import com.liferay.osb.asah.common.entity.Asset;
import com.liferay.osb.asah.common.entity.Segment;
import com.liferay.osb.asah.common.repository.AssetRepository;
import com.liferay.osb.asah.common.repository.BQFieldMappingRepository;
import com.liferay.osb.asah.common.repository.BQMembershipChangeRepository;
import com.liferay.osb.asah.common.repository.ChannelRepository;
import com.liferay.osb.asah.common.repository.DXPEntityRepository;
import com.liferay.osb.asah.common.repository.DataSourceRepository;
import com.liferay.osb.asah.common.repository.SegmentRepository;
import com.liferay.osb.asah.test.util.annotation.RepositoryResource;
import com.liferay.osb.asah.test.util.faro.FaroInfoTestUtil;

import io.restassured.http.Method;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import org.json.JSONArray;
import org.json.JSONObject;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;

/**
 * @author Vishal Reddy
 */
public class IndividualSegmentsRestControllerTest
	extends BaseRestControllerTestCase {

	@Disabled
	@RepositoryResource(
		repositoryClass = DataSourceRepository.class,
		resourcePath = "osbasahfaroinfo/data_sources.json"
	)
	@Test
	public void testExpandReferencedObjects() throws Exception {
		_assetRepository.save(
			_objectMapper.convertValue(
				FaroInfoTestUtil.buildAssetJSONObject("Page", 1L),
				Asset.class));

		// TODO Add BQFieldMapping "email", "Text"

		Segment segment = new Segment();

		segment.setReferencedFieldMappingFieldNames(null);

		segment = _segmentRepository.save(segment);

		SegmentDTO segmentDTO = _individualSegmentsRestController.getSegmentDTO(
			segment.getId(), "referenced-objects");

		Map<String, Object> embedded = segmentDTO.getEmbedded();

		JSONObject referencedObjectsJSONObject = (JSONObject)embedded.get(
			"referenced-objects");

		_assertEmptyJSONArray(
			referencedObjectsJSONObject.getJSONArray("assets"));
		_assertEmptyJSONArray(
			referencedObjectsJSONObject.getJSONArray("groups"));
		_assertEmptyJSONArray(
			referencedObjectsJSONObject.getJSONArray("organizations"));
		_assertEmptyJSONArray(
			referencedObjectsJSONObject.getJSONArray("roles"));
		_assertEmptyJSONArray(
			referencedObjectsJSONObject.getJSONArray("teams"));
		_assertEmptyJSONArray(
			referencedObjectsJSONObject.getJSONArray("user-groups"));
		_assertEmptyJSONArray(
			referencedObjectsJSONObject.getJSONArray("users"));
	}

	/**
	 * The JSON files are named after the WeDeploy collections that they are
	 * populated into. The JSON files were generated by running the
	 * DXPIndividualsNanite test, and retrieved from the WeDeploy data container
	 * before the tests cleaned up the data.
	 */
	@Disabled
	@RepositoryResource(
		repositoryClass = DataSourceRepository.class,
		resourcePath = "osbasahfaroinfo/data_sources.json"
	)
	@RepositoryResource(
		repositoryClass = BQFieldMappingRepository.class,
		resourcePath = "osbasahfaroinfo/field_mappings.json"
	)
	@RepositoryResource(
		repositoryClass = DXPEntityRepository.class,
		resourcePath = "osbasahdxpraw/users.json"
	)
	@RepositoryResource(
		repositoryClass = SegmentRepository.class,
		resourcePath = "osbasahfaroinfo/individual_segments.json"
	)
	@Test
	public void testGetIndividualSegments() {
		validateIndividuals(
			getValidatableResponse(
				Method.GET,
				"/api/1.0/individual-segments/327968823603500655/individuals"));
	}

	@Disabled
	@RepositoryResource(
		repositoryClass = BQMembershipChangeRepository.class,
		resourcePath = "osbasahfaroinfo/bq_membership_changes_1.json"
	)
	@RepositoryResource(
		repositoryClass = ChannelRepository.class,
		resourcePath = "osbasahfaroinfo/channels.json"
	)
	@RepositoryResource(
		repositoryClass = DataSourceRepository.class,
		resourcePath = "osbasahfaroinfo/data_sources_1.json"
	)
	@RepositoryResource(
		repositoryClass = SegmentRepository.class,
		resourcePath = "osbasahfaroinfo/individual_segments_1.json"
	)
	@Test
	public void testGetIndividualSegmentsForDataSourceId() {
		JSONObject responseJSONObject = _objectMapper.convertValue(
			_individualSegmentsRestController.getSegmentDTOPageDTO(
				327968823603501234L, "((individualCount ge 1))", 0, 20,
				new String[] {"dateModified"}),
			JSONObject.class);

		JSONObject embeddedJSONObject = responseJSONObject.getJSONObject(
			"_embedded");

		JSONArray individualSegmentsJSONArray = embeddedJSONObject.getJSONArray(
			"individual-segments");

		Assertions.assertEquals(2, individualSegmentsJSONArray.length());

		responseJSONObject = _objectMapper.convertValue(
			_individualSegmentsRestController.getSegmentDTOPageDTO(
				331238757269547423L, "((individualCount ge 1))", 0, 20,
				new String[] {"dateModified"}),
			JSONObject.class);

		embeddedJSONObject = responseJSONObject.getJSONObject("_embedded");

		individualSegmentsJSONArray = embeddedJSONObject.getJSONArray(
			"individual-segments");

		Assertions.assertEquals(1, individualSegmentsJSONArray.length());
	}

	@RepositoryResource(
		repositoryClass = BQMembershipChangeRepository.class,
		resourcePath = "osbasahfaroinfo/bq_membership_changes_1.json"
	)
	@RepositoryResource(
		repositoryClass = ChannelRepository.class,
		resourcePath = "osbasahfaroinfo/channels.json"
	)
	@RepositoryResource(
		repositoryClass = SegmentRepository.class,
		resourcePath = "osbasahfaroinfo/individual_segments_1.json"
	)
	@Test
	public void testGetSegmentDTO1() throws Exception {
		SegmentDTO segmentDTO = _individualSegmentsRestController.getSegmentDTO(
			327968823603500655L, "referenced-objects");

		long activeIdentitiesCount = Optional.ofNullable(
			segmentDTO.getActiveIdentitiesCount()
		).orElse(
			-1L
		);

		Assertions.assertEquals(0, activeIdentitiesCount);

		long anonymousIdentitiesCount = Optional.ofNullable(
			segmentDTO.getAnonymousIdentitiesCount()
		).orElse(
			-1L
		);

		Assertions.assertEquals(9L, anonymousIdentitiesCount);

		long identitiesCount = Optional.ofNullable(
			segmentDTO.getIdentitiesCount()
		).orElse(
			-1L
		);

		Assertions.assertEquals(11L, identitiesCount);

		long knownIdentitiesCount = Optional.ofNullable(
			segmentDTO.getKnownIdentitiesCount()
		).orElse(
			-1L
		);

		Assertions.assertEquals(2L, knownIdentitiesCount);

		Assertions.assertEquals("d-age-gt-50", segmentDTO.getName());

		Set<String> referencedDataSourceIds =
			segmentDTO.getReferencedDataSourceIds();

		Assertions.assertTrue(referencedDataSourceIds.isEmpty());

		Set<String> referencedFieldMappingFieldNames =
			segmentDTO.getReferencedFieldMappingFieldNames();

		Assertions.assertTrue(referencedFieldMappingFieldNames.isEmpty());
	}

	@RepositoryResource(
		repositoryClass = BQMembershipChangeRepository.class,
		resourcePath = "osbasahfaroinfo/bq_membership_changes_1.json"
	)
	@RepositoryResource(
		repositoryClass = SegmentRepository.class,
		resourcePath = "osbasahfaroinfo/individual_segments_3.json"
	)
	@Test
	public void testGetSegmentDTO2() throws Exception {
		SegmentDTO segmentDTO = _individualSegmentsRestController.getSegmentDTO(
			327968823603500655L, null);

		Assertions.assertEquals(2L, segmentDTO.getKnownIdentitiesCount());
	}

	@RepositoryResource(
		repositoryClass = BQMembershipChangeRepository.class,
		resourcePath = "osbasahfaroinfo/bq_membership_changes_2.json"
	)
	@RepositoryResource(
		repositoryClass = ChannelRepository.class,
		resourcePath = "osbasahfaroinfo/channels_2.json"
	)
	@RepositoryResource(
		repositoryClass = SegmentRepository.class,
		resourcePath = "osbasahfaroinfo/individual_segments_2.json"
	)
	@Test
	public void testGetSegmentDTOCreatedToday() throws Exception {
		SegmentDTO segmentDTO = _individualSegmentsRestController.getSegmentDTO(
			1L, null);

		long anonymousIdentitiesCount = Optional.ofNullable(
			segmentDTO.getAnonymousIdentitiesCount()
		).orElse(
			-1L
		);

		Assertions.assertEquals(0L, anonymousIdentitiesCount);

		long identitiesCount = Optional.ofNullable(
			segmentDTO.getIdentitiesCount()
		).orElse(
			-1L
		);

		Assertions.assertEquals(6L, identitiesCount);

		long knownIdentitiesCount = Optional.ofNullable(
			segmentDTO.getKnownIdentitiesCount()
		).orElse(
			-1L
		);

		Assertions.assertEquals(6L, knownIdentitiesCount);
	}

	@RepositoryResource(
		repositoryClass = BQMembershipChangeRepository.class,
		resourcePath = "osbasahfaroinfo/bq_membership_changes_2.json"
	)
	@RepositoryResource(
		repositoryClass = ChannelRepository.class,
		resourcePath = "osbasahfaroinfo/channels_2.json"
	)
	@RepositoryResource(
		repositoryClass = SegmentRepository.class,
		resourcePath = "osbasahfaroinfo/individual_segments_2.json"
	)
	@Test
	public void testGetSegmentDTOPageDTO1() {
		PageDTO<SegmentDTO> pageDTO =
			_individualSegmentsRestController.getSegmentDTOPageDTO(
				1L, "individualCount ge '1' and status = 'ACTIVE'", 0, 50,
				new String[0]);

		Map<String, SegmentDTO> content = pageDTO.getContent();

		SegmentDTO embedded = content.get("_embedded");

		Set<SegmentDTO> segmentDTOs = embedded.getSegmentDTOs();

		Assertions.assertEquals(2, segmentDTOs.size(), segmentDTOs.toString());

		Stream<SegmentDTO> stream = segmentDTOs.stream();

		List<String> ids = stream.map(
			SegmentDTO::getId
		).collect(
			Collectors.toList()
		);

		Assertions.assertTrue(ids.containsAll(Arrays.asList("1", "2")));

		for (SegmentDTO segmentDTO : segmentDTOs) {
			long anonymousIdentitiesCount = Optional.ofNullable(
				segmentDTO.getAnonymousIdentitiesCount()
			).orElse(
				-1L
			);

			long identitiesCount = Optional.ofNullable(
				segmentDTO.getIdentitiesCount()
			).orElse(
				-1L
			);

			long knownIdentitiesCount = Optional.ofNullable(
				segmentDTO.getKnownIdentitiesCount()
			).orElse(
				-1L
			);

			if (Objects.equals(segmentDTO.getId(), "1")) {
				Assertions.assertEquals(0L, anonymousIdentitiesCount);
				Assertions.assertEquals(6L, identitiesCount);
				Assertions.assertEquals(6L, knownIdentitiesCount);
			}
			else if (Objects.equals(segmentDTO.getId(), "2")) {
				Assertions.assertEquals(0L, anonymousIdentitiesCount);
				Assertions.assertEquals(6L, identitiesCount);
				Assertions.assertEquals(6L, knownIdentitiesCount);
			}
		}
	}

	@RepositoryResource(
		repositoryClass = BQMembershipChangeRepository.class,
		resourcePath = "osbasahfaroinfo/bq_membership_changes_1.json"
	)
	@RepositoryResource(
		repositoryClass = SegmentRepository.class,
		resourcePath = "osbasahfaroinfo/individual_segments_3.json"
	)
	@Test
	public void testGetSegmentDTOPageDTO2() {
		PageDTO<SegmentDTO> pageDTO =
			_individualSegmentsRestController.getSegmentDTOPageDTO(
				1L, null, 0, 50, new String[0]);

		Map<String, SegmentDTO> content = pageDTO.getContent();

		SegmentDTO embedded = content.get("_embedded");

		List<SegmentDTO> segmentDTOs = new ArrayList(embedded.getSegmentDTOs());

		Assertions.assertEquals(1, segmentDTOs.size(), segmentDTOs.toString());

		SegmentDTO segmentDTO = segmentDTOs.get(0);

		Assertions.assertEquals(2L, segmentDTO.getKnownIdentitiesCount());
	}

	private void _assertEmptyJSONArray(JSONArray jsonArray) {
		Assertions.assertTrue(jsonArray.isEmpty());
	}

	@Autowired
	private AssetRepository _assetRepository;

	@Autowired
	@Qualifier(
		"com.liferay.osb.asah.backend.rest.controller.api.data.source.v1.IndividualSegmentsRestController"
	)
	private IndividualSegmentsRestController _individualSegmentsRestController;

	@Autowired
	private ObjectMapper _objectMapper;

	@Autowired
	private SegmentRepository _segmentRepository;

}