/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.asah.backend.rest.controller.api.data.source.v1.test;

import com.liferay.osb.asah.common.repository.BQFieldMappingRepository;
import com.liferay.osb.asah.common.repository.DXPEntityRepository;
import com.liferay.osb.asah.common.repository.DataSourceRepository;
import com.liferay.osb.asah.common.repository.SegmentRepository;
import com.liferay.osb.asah.test.util.annotation.BQSQLResource;
import com.liferay.osb.asah.test.util.annotation.RepositoryResource;

import io.restassured.http.Method;

import org.hamcrest.Matchers;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * @author Vishal Reddy
 */
public class IndividualsRestControllerTest extends BaseRestControllerTestCase {

	/**
	 * The JSON files are named after the WeDeploy collections that they are
	 * populated into. The JSON files were generated by running the
	 * DXPIndividualsNanite test, and retrieved from the WeDeploy data container
	 * before the tests cleaned up the data.
	 */
	@Disabled
	@RepositoryResource(
		repositoryClass = DataSourceRepository.class,
		resourcePath = "osbasahfaroinfo/data_sources.json"
	)
	@RepositoryResource(
		repositoryClass = BQFieldMappingRepository.class,
		resourcePath = "osbasahfaroinfo/field_mappings.json"
	)
	@RepositoryResource(
		repositoryClass = DXPEntityRepository.class,
		resourcePath = "osbasahdxpraw/users.json"
	)
	@RepositoryResource(
		repositoryClass = SegmentRepository.class,
		resourcePath = "osbasahfaroinfo/individual_segments.json"
	)
	@Test
	public void testGetIndividuals() {
		validateIndividuals(
			getValidatableResponse(Method.GET, "/api/1.0/individuals"));
	}

	@BQSQLResource(resourcePath = "individuals_with_filter_test.sql")
	@RepositoryResource(
		repositoryClass = SegmentRepository.class,
		resourcePath = "osbasahfaroinfo/individual_segments.json"
	)
	@Test
	public void testGetIndividualsWithFilter() {

		// Lower case to upper case conversion

		_validateTotalElements(
			"((contains(demographics/givenName/value,'test')))", 1);

		// Upper case to lower case conversion

		_validateTotalElements(
			"((contains(demographics/givenName/value,'TEST')))", 1);

		// Mixed case

		_validateTotalElements(
			"((contains(demographics/givenName/value,'tEsT')))", 1);

		// Characters out of order

		_validateTotalElements(
			"((contains(demographics/givenName/value,'tset')))", 0);

		// Subsequence missing interior characters

		_validateTotalElements(
			"((contains(demographics/givenName/value,'tet')))", 0);

		// Symbols with mixed case

		_validateTotalElements(
			"((contains(demographics/email/value,'.teSt@L')))", 1);

		// Wrong symbol

		_validateTotalElements(
			"((contains(demographics/email/value,'>test@l')))", 0);

		// Regex symbols escaped

		//_validateTotalElements(
		//	"((contains(demographics/email/value,'.*')))", 0);

		// Individuals in a specific data source

		_validateTotalElements("((dataSourceId eq '337984445922213329'))", 2);

		_validateTotalElements("((dataSourceId eq '337984445922213328'))", 0);

		// Individuals with a specific individual PK

		_validateTotalElements(
			"((dataSourceIndividualPKs/individualPKs eq " +
				"'953be104-5540-abf8-59b8-55f895200acc'))",
			0);
	}

	private void _validateTotalElements(String filterString, int elements) {
		validateResponse(
			Matchers.is(elements), "page.totalElements",
			getValidatableResponse(
				Method.GET, "/api/1.0/individuals?filter=" + filterString));
	}

}