UPDATE BQEvent SET userId = '${new_identity_id}' WHERE userId = '${old_identity_id}' AND eventDate >= timestamp '${start_date}';
UPDATE BQIdentityActivitySummary SET identityId = '${new_identity_id}' WHERE identityId = '${old_identity_id}' AND firstActivityDate >= timestamp '${start_date}';
UPDATE BQIdentityInterestPage SET identityId = '${new_identity_id}' WHERE identityId = '${old_identity_id}';
UPDATE BQIdentityInterestScore SET identityId = '${new_identity_id}' WHERE identityId = '${old_identity_id}' AND recordedDate >= DATE('${start_date}');
UPDATE BQIdentity_Raw SET id = '${new_identity_id}' WHERE id = '${old_identity_id}' AND createDate >= timestamp '${start_date}';
UPDATE BQSession SET userId = '${new_identity_id}' WHERE userId = '${old_identity_id}' AND sessionStart >= timestamp '${start_date}';
UPDATE BQSessionInterestScore SET identityId = '${new_identity_id}' WHERE identityId = '${old_identity_id}' AND recordedDate >= DATE('${start_date}');
UPDATE BlogDaily SET userId = '${new_identity_id}' WHERE userId = '${old_identity_id}' AND eventDate >= timestamp '${start_date}';
UPDATE DocumentLibraryDaily SET userId = '${new_identity_id}' WHERE userId = '${old_identity_id}' AND eventDate >= timestamp '${start_date}';
UPDATE FormDaily SET userId = '${new_identity_id}' WHERE userId = '${old_identity_id}' AND eventDate >= timestamp '${start_date}';
UPDATE JournalDaily SET userId = '${new_identity_id}' WHERE userId = '${old_identity_id}' AND eventDate >= timestamp '${start_date}';
UPDATE PageDaily SET userId = '${new_identity_id}' WHERE userId = '${old_identity_id}' AND eventDate >= timestamp '${start_date}';