/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the FinderWhereClauseEntry service. Represents a row in the &quot;FinderWhereClauseEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.FinderWhereClauseEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.FinderWhereClauseEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FinderWhereClauseEntry
 * @generated
 */
@ProviderType
public interface FinderWhereClauseEntryModel
	extends BaseModel<FinderWhereClauseEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a finder where clause entry model instance should use the {@link FinderWhereClauseEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this finder where clause entry.
	 *
	 * @return the primary key of this finder where clause entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this finder where clause entry.
	 *
	 * @param primaryKey the primary key of this finder where clause entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the finder where clause entry ID of this finder where clause entry.
	 *
	 * @return the finder where clause entry ID of this finder where clause entry
	 */
	public long getFinderWhereClauseEntryId();

	/**
	 * Sets the finder where clause entry ID of this finder where clause entry.
	 *
	 * @param finderWhereClauseEntryId the finder where clause entry ID of this finder where clause entry
	 */
	public void setFinderWhereClauseEntryId(long finderWhereClauseEntryId);

	/**
	 * Returns the name of this finder where clause entry.
	 *
	 * @return the name of this finder where clause entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this finder where clause entry.
	 *
	 * @param name the name of this finder where clause entry
	 */
	public void setName(String name);

	/**
	 * Returns the nickname of this finder where clause entry.
	 *
	 * @return the nickname of this finder where clause entry
	 */
	@AutoEscape
	public String getNickname();

	/**
	 * Sets the nickname of this finder where clause entry.
	 *
	 * @param nickname the nickname of this finder where clause entry
	 */
	public void setNickname(String nickname);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(FinderWhereClauseEntry finderWhereClauseEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<FinderWhereClauseEntry> toCacheModel();

	@Override
	public FinderWhereClauseEntry toEscapedModel();

	@Override
	public FinderWhereClauseEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}