/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the NullConvertibleEntry service. Represents a row in the &quot;NullConvertibleEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.NullConvertibleEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.NullConvertibleEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NullConvertibleEntry
 * @generated
 */
@ProviderType
public interface NullConvertibleEntryModel
	extends BaseModel<NullConvertibleEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a null convertible entry model instance should use the {@link NullConvertibleEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this null convertible entry.
	 *
	 * @return the primary key of this null convertible entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this null convertible entry.
	 *
	 * @param primaryKey the primary key of this null convertible entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the null convertible entry ID of this null convertible entry.
	 *
	 * @return the null convertible entry ID of this null convertible entry
	 */
	public long getNullConvertibleEntryId();

	/**
	 * Sets the null convertible entry ID of this null convertible entry.
	 *
	 * @param nullConvertibleEntryId the null convertible entry ID of this null convertible entry
	 */
	public void setNullConvertibleEntryId(long nullConvertibleEntryId);

	/**
	 * Returns the name of this null convertible entry.
	 *
	 * @return the name of this null convertible entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this null convertible entry.
	 *
	 * @param name the name of this null convertible entry
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(NullConvertibleEntry nullConvertibleEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<NullConvertibleEntry> toCacheModel();

	@Override
	public NullConvertibleEntry toEscapedModel();

	@Override
	public NullConvertibleEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}