/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the RedundantIndexEntry service. Represents a row in the &quot;RedundantIndexEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.RedundantIndexEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.RedundantIndexEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RedundantIndexEntry
 * @generated
 */
@ProviderType
public interface RedundantIndexEntryModel
	extends BaseModel<RedundantIndexEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a redundant index entry model instance should use the {@link RedundantIndexEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this redundant index entry.
	 *
	 * @return the primary key of this redundant index entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this redundant index entry.
	 *
	 * @param primaryKey the primary key of this redundant index entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the redundant index entry ID of this redundant index entry.
	 *
	 * @return the redundant index entry ID of this redundant index entry
	 */
	public long getRedundantIndexEntryId();

	/**
	 * Sets the redundant index entry ID of this redundant index entry.
	 *
	 * @param redundantIndexEntryId the redundant index entry ID of this redundant index entry
	 */
	public void setRedundantIndexEntryId(long redundantIndexEntryId);

	/**
	 * Returns the company ID of this redundant index entry.
	 *
	 * @return the company ID of this redundant index entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this redundant index entry.
	 *
	 * @param companyId the company ID of this redundant index entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this redundant index entry.
	 *
	 * @return the name of this redundant index entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this redundant index entry.
	 *
	 * @param name the name of this redundant index entry
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(RedundantIndexEntry redundantIndexEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<RedundantIndexEntry> toCacheModel();

	@Override
	public RedundantIndexEntry toEscapedModel();

	@Override
	public RedundantIndexEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}