/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the RenameFinderColumnEntry service. Represents a row in the &quot;RenameFinderColumnEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.RenameFinderColumnEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.RenameFinderColumnEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RenameFinderColumnEntry
 * @generated
 */
@ProviderType
public interface RenameFinderColumnEntryModel
	extends BaseModel<RenameFinderColumnEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rename finder column entry model instance should use the {@link RenameFinderColumnEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this rename finder column entry.
	 *
	 * @return the primary key of this rename finder column entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rename finder column entry.
	 *
	 * @param primaryKey the primary key of this rename finder column entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rename finder column entry ID of this rename finder column entry.
	 *
	 * @return the rename finder column entry ID of this rename finder column entry
	 */
	public long getRenameFinderColumnEntryId();

	/**
	 * Sets the rename finder column entry ID of this rename finder column entry.
	 *
	 * @param renameFinderColumnEntryId the rename finder column entry ID of this rename finder column entry
	 */
	public void setRenameFinderColumnEntryId(long renameFinderColumnEntryId);

	/**
	 * Returns the group ID of this rename finder column entry.
	 *
	 * @return the group ID of this rename finder column entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this rename finder column entry.
	 *
	 * @param groupId the group ID of this rename finder column entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the renamed column of this rename finder column entry.
	 *
	 * @return the renamed column of this rename finder column entry
	 */
	@AutoEscape
	public String getRenamedColumn();

	/**
	 * Sets the renamed column of this rename finder column entry.
	 *
	 * @param renamedColumn the renamed column of this rename finder column entry
	 */
	public void setRenamedColumn(String renamedColumn);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(RenameFinderColumnEntry renameFinderColumnEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<RenameFinderColumnEntry> toCacheModel();

	@Override
	public RenameFinderColumnEntry toEscapedModel();

	@Override
	public RenameFinderColumnEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}