/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.commerce.bom.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.commerce.bom.model.CommerceBOMFolder;
import com.liferay.commerce.bom.service.CommerceBOMFolderLocalServiceUtil;

/**
 * The extended model base implementation for the CommerceBOMFolder service. Represents a row in the &quot;CommerceBOMFolder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceBOMFolderImpl}.
 * </p>
 *
 * @author Luca Pellizzon
 * @see CommerceBOMFolderImpl
 * @see CommerceBOMFolder
 * @generated
 */
@ProviderType
public abstract class CommerceBOMFolderBaseImpl
	extends CommerceBOMFolderModelImpl implements CommerceBOMFolder {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce bom folder model instance should use the {@link CommerceBOMFolder} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CommerceBOMFolderLocalServiceUtil.addCommerceBOMFolder(this);
		}
		else {
			CommerceBOMFolderLocalServiceUtil.updateCommerceBOMFolder(this);
		}
	}
}