addons:
    chrome: stable
before_install:
    - mv $HOME/build $HOME/faro
    - TRAVIS_BUILD_DIR=$HOME/faro/$TRAVIS_REPO_SLUG
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
    timeout: 600
dist: bionic
env:
    global:
        - NODE_OPTIONS=--max_old_space_size=2048
jdk: oraclejdk8
jobs:
    include:
        - stage: push docker image
          if: branch = 7.1.x AND type = push
          script: ./gradlew pushAppDockerImage
        - stage: source formatting checks
          script: ./gradlew packageRunLint checkSourceFormatting pmdMain pmdTest pmdTestIntegration
        - stage: javascript tests
          script: ./gradlew packageRunWebpack packageRunTest
          after_success:
              - test $TRAVIS_BRANCH = "7.1.x" &&
                test $TRAVIS_EVENT_TYPE = "push" &&
                test $TRAVIS_REPO_SLUG = "liferay/com-liferay-osb-faro-private" &&
                ./gradlew packageRunCoveralls
language: java
os: linux
services:
    - docker