auth.verifier.pipeline=com.liferay.osb.loop.token.auth.internal.auto.login.TokenAuthAutoLogin
auto.login.hooks=com.liferay.osb.loop.token.auth.internal.auto.login.TokenAuthAutoLogin

auth.verifier.TokenAuthAutoLogin.urls.includes=/api/jsonws/*