logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr(%X{osbAsahProjectId:-none}){green} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}
management.endpoint.health.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoints.enabled-by-default=false
management.security.enabled=false
osb.asah.seo.semrush.databases.limit=5
osb.asah.seo.semrush.url.adwords.display.limit=10
osb.asah.seo.semrush.url.organic.display.limit=5