/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.pricing.model.impl;

import com.liferay.commerce.pricing.model.CommercePricingClassRel;
import com.liferay.commerce.pricing.model.CommercePricingClassRelModel;
import com.liferay.commerce.pricing.model.CommercePricingClassRelSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CommercePricingClassRel service. Represents a row in the &quot;CommercePricingClassRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CommercePricingClassRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommercePricingClassRelImpl}.
 * </p>
 *
 * @author Riccardo Alberti
 * @see CommercePricingClassRelImpl
 * @generated
 */
@JSON(strict = true)
public class CommercePricingClassRelModelImpl
	extends BaseModelImpl<CommercePricingClassRel>
	implements CommercePricingClassRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce pricing class rel model instance should use the <code>CommercePricingClassRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "CommercePricingClassRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"commercePricingClassRelId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"commercePricingClassId", Types.BIGINT}, {"classNameId", Types.BIGINT},
		{"classPK", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("commercePricingClassRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("commercePricingClassId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CommercePricingClassRel (commercePricingClassRelId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,commercePricingClassId LONG,classNameId LONG,classPK LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table CommercePricingClassRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commercePricingClassRel.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CommercePricingClassRel.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.pricing.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.commerce.pricing.model.CommercePricingClassRel"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.pricing.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.commerce.pricing.model.CommercePricingClassRel"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.pricing.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.commerce.pricing.model.CommercePricingClassRel"),
		true);

	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;

	public static final long CLASSPK_COLUMN_BITMASK = 2L;

	public static final long COMMERCEPRICINGCLASSID_COLUMN_BITMASK = 4L;

	public static final long CREATEDATE_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CommercePricingClassRel toModel(
		CommercePricingClassRelSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		CommercePricingClassRel model = new CommercePricingClassRelImpl();

		model.setCommercePricingClassRelId(
			soapModel.getCommercePricingClassRelId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCommercePricingClassId(soapModel.getCommercePricingClassId());
		model.setClassNameId(soapModel.getClassNameId());
		model.setClassPK(soapModel.getClassPK());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CommercePricingClassRel> toModels(
		CommercePricingClassRelSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<CommercePricingClassRel> models =
			new ArrayList<CommercePricingClassRel>(soapModels.length);

		for (CommercePricingClassRelSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.commerce.pricing.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.commerce.pricing.model.CommercePricingClassRel"));

	public CommercePricingClassRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commercePricingClassRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommercePricingClassRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commercePricingClassRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommercePricingClassRel.class;
	}

	@Override
	public String getModelClassName() {
		return CommercePricingClassRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CommercePricingClassRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CommercePricingClassRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommercePricingClassRel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CommercePricingClassRel)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CommercePricingClassRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CommercePricingClassRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CommercePricingClassRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CommercePricingClassRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CommercePricingClassRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CommercePricingClassRel>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CommercePricingClassRel.class.getClassLoader(),
			CommercePricingClassRel.class, ModelWrapper.class);

		try {
			Constructor<CommercePricingClassRel> constructor =
				(Constructor<CommercePricingClassRel>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<CommercePricingClassRel, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<CommercePricingClassRel, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<CommercePricingClassRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CommercePricingClassRel, Object>>();
		Map<String, BiConsumer<CommercePricingClassRel, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<CommercePricingClassRel, ?>>();

		attributeGetterFunctions.put(
			"commercePricingClassRelId",
			new Function<CommercePricingClassRel, Object>() {

				@Override
				public Object apply(
					CommercePricingClassRel commercePricingClassRel) {

					return commercePricingClassRel.
						getCommercePricingClassRelId();
				}

			});
		attributeSetterBiConsumers.put(
			"commercePricingClassRelId",
			new BiConsumer<CommercePricingClassRel, Object>() {

				@Override
				public void accept(
					CommercePricingClassRel commercePricingClassRel,
					Object commercePricingClassRelIdObject) {

					commercePricingClassRel.setCommercePricingClassRelId(
						(Long)commercePricingClassRelIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<CommercePricingClassRel, Object>() {

				@Override
				public Object apply(
					CommercePricingClassRel commercePricingClassRel) {

					return commercePricingClassRel.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<CommercePricingClassRel, Object>() {

				@Override
				public void accept(
					CommercePricingClassRel commercePricingClassRel,
					Object companyIdObject) {

					commercePricingClassRel.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<CommercePricingClassRel, Object>() {

				@Override
				public Object apply(
					CommercePricingClassRel commercePricingClassRel) {

					return commercePricingClassRel.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<CommercePricingClassRel, Object>() {

				@Override
				public void accept(
					CommercePricingClassRel commercePricingClassRel,
					Object userIdObject) {

					commercePricingClassRel.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<CommercePricingClassRel, Object>() {

				@Override
				public Object apply(
					CommercePricingClassRel commercePricingClassRel) {

					return commercePricingClassRel.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<CommercePricingClassRel, Object>() {

				@Override
				public void accept(
					CommercePricingClassRel commercePricingClassRel,
					Object userNameObject) {

					commercePricingClassRel.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<CommercePricingClassRel, Object>() {

				@Override
				public Object apply(
					CommercePricingClassRel commercePricingClassRel) {

					return commercePricingClassRel.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<CommercePricingClassRel, Object>() {

				@Override
				public void accept(
					CommercePricingClassRel commercePricingClassRel,
					Object createDateObject) {

					commercePricingClassRel.setCreateDate(
						(Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<CommercePricingClassRel, Object>() {

				@Override
				public Object apply(
					CommercePricingClassRel commercePricingClassRel) {

					return commercePricingClassRel.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<CommercePricingClassRel, Object>() {

				@Override
				public void accept(
					CommercePricingClassRel commercePricingClassRel,
					Object modifiedDateObject) {

					commercePricingClassRel.setModifiedDate(
						(Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"commercePricingClassId",
			new Function<CommercePricingClassRel, Object>() {

				@Override
				public Object apply(
					CommercePricingClassRel commercePricingClassRel) {

					return commercePricingClassRel.getCommercePricingClassId();
				}

			});
		attributeSetterBiConsumers.put(
			"commercePricingClassId",
			new BiConsumer<CommercePricingClassRel, Object>() {

				@Override
				public void accept(
					CommercePricingClassRel commercePricingClassRel,
					Object commercePricingClassIdObject) {

					commercePricingClassRel.setCommercePricingClassId(
						(Long)commercePricingClassIdObject);
				}

			});
		attributeGetterFunctions.put(
			"classNameId",
			new Function<CommercePricingClassRel, Object>() {

				@Override
				public Object apply(
					CommercePricingClassRel commercePricingClassRel) {

					return commercePricingClassRel.getClassNameId();
				}

			});
		attributeSetterBiConsumers.put(
			"classNameId",
			new BiConsumer<CommercePricingClassRel, Object>() {

				@Override
				public void accept(
					CommercePricingClassRel commercePricingClassRel,
					Object classNameIdObject) {

					commercePricingClassRel.setClassNameId(
						(Long)classNameIdObject);
				}

			});
		attributeGetterFunctions.put(
			"classPK",
			new Function<CommercePricingClassRel, Object>() {

				@Override
				public Object apply(
					CommercePricingClassRel commercePricingClassRel) {

					return commercePricingClassRel.getClassPK();
				}

			});
		attributeSetterBiConsumers.put(
			"classPK",
			new BiConsumer<CommercePricingClassRel, Object>() {

				@Override
				public void accept(
					CommercePricingClassRel commercePricingClassRel,
					Object classPKObject) {

					commercePricingClassRel.setClassPK((Long)classPKObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getCommercePricingClassRelId() {
		return _commercePricingClassRelId;
	}

	@Override
	public void setCommercePricingClassRelId(long commercePricingClassRelId) {
		_commercePricingClassRelId = commercePricingClassRelId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCommercePricingClassId() {
		return _commercePricingClassId;
	}

	@Override
	public void setCommercePricingClassId(long commercePricingClassId) {
		_columnBitmask |= COMMERCEPRICINGCLASSID_COLUMN_BITMASK;

		if (!_setOriginalCommercePricingClassId) {
			_setOriginalCommercePricingClassId = true;

			_originalCommercePricingClassId = _commercePricingClassId;
		}

		_commercePricingClassId = commercePricingClassId;
	}

	public long getOriginalCommercePricingClassId() {
		return _originalCommercePricingClassId;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@JSON
	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	@JSON
	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CommercePricingClassRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommercePricingClassRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CommercePricingClassRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommercePricingClassRelImpl commercePricingClassRelImpl =
			new CommercePricingClassRelImpl();

		commercePricingClassRelImpl.setCommercePricingClassRelId(
			getCommercePricingClassRelId());
		commercePricingClassRelImpl.setCompanyId(getCompanyId());
		commercePricingClassRelImpl.setUserId(getUserId());
		commercePricingClassRelImpl.setUserName(getUserName());
		commercePricingClassRelImpl.setCreateDate(getCreateDate());
		commercePricingClassRelImpl.setModifiedDate(getModifiedDate());
		commercePricingClassRelImpl.setCommercePricingClassId(
			getCommercePricingClassId());
		commercePricingClassRelImpl.setClassNameId(getClassNameId());
		commercePricingClassRelImpl.setClassPK(getClassPK());

		commercePricingClassRelImpl.resetOriginalValues();

		return commercePricingClassRelImpl;
	}

	@Override
	public int compareTo(CommercePricingClassRel commercePricingClassRel) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), commercePricingClassRel.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CommercePricingClassRel)) {
			return false;
		}

		CommercePricingClassRel commercePricingClassRel =
			(CommercePricingClassRel)obj;

		long primaryKey = commercePricingClassRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CommercePricingClassRelModelImpl commercePricingClassRelModelImpl =
			this;

		commercePricingClassRelModelImpl._setModifiedDate = false;

		commercePricingClassRelModelImpl._originalCommercePricingClassId =
			commercePricingClassRelModelImpl._commercePricingClassId;

		commercePricingClassRelModelImpl._setOriginalCommercePricingClassId =
			false;

		commercePricingClassRelModelImpl._originalClassNameId =
			commercePricingClassRelModelImpl._classNameId;

		commercePricingClassRelModelImpl._setOriginalClassNameId = false;

		commercePricingClassRelModelImpl._originalClassPK =
			commercePricingClassRelModelImpl._classPK;

		commercePricingClassRelModelImpl._setOriginalClassPK = false;

		commercePricingClassRelModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CommercePricingClassRel> toCacheModel() {
		CommercePricingClassRelCacheModel commercePricingClassRelCacheModel =
			new CommercePricingClassRelCacheModel();

		commercePricingClassRelCacheModel.commercePricingClassRelId =
			getCommercePricingClassRelId();

		commercePricingClassRelCacheModel.companyId = getCompanyId();

		commercePricingClassRelCacheModel.userId = getUserId();

		commercePricingClassRelCacheModel.userName = getUserName();

		String userName = commercePricingClassRelCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			commercePricingClassRelCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			commercePricingClassRelCacheModel.createDate = createDate.getTime();
		}
		else {
			commercePricingClassRelCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			commercePricingClassRelCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			commercePricingClassRelCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		commercePricingClassRelCacheModel.commercePricingClassId =
			getCommercePricingClassId();

		commercePricingClassRelCacheModel.classNameId = getClassNameId();

		commercePricingClassRelCacheModel.classPK = getClassPK();

		return commercePricingClassRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CommercePricingClassRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CommercePricingClassRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommercePricingClassRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((CommercePricingClassRel)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CommercePricingClassRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CommercePricingClassRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommercePricingClassRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((CommercePricingClassRel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CommercePricingClassRel>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private long _commercePricingClassRelId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _commercePricingClassId;
	private long _originalCommercePricingClassId;
	private boolean _setOriginalCommercePricingClassId;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private long _columnBitmask;
	private CommercePricingClassRel _escapedModel;

}