dependencies {
	compileOnly group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.1.0"
	compileOnly group: "com.fasterxml.jackson.core", name: "jackson-annotations", version: "2.9.10"
	compileOnly group: "com.fasterxml.jackson.core", name: "jackson-core", version: "2.9.10"
	compileOnly group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.9.10.8"
	compileOnly group: "com.liferay", name: "com.liferay.petra.string", version: "2.1.7"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "3.97.4"
	compileOnly group: "org.apache.httpcomponents", name: "httpclient", version: "4.5.13"
	compileOnly group: "org.apache.httpcomponents", name: "httpcore", version: "4.4.5"
	compileOnly group: "org.apache.httpcomponents", name: "httpmime", version: "4.5.2"
	compileOnly group: "org.springframework", name: "spring-core", version: "5.2.12.RELEASE"
	compileOnly group: "org.springframework", name: "spring-web", version: "5.2.12.RELEASE"
	compileOnly group: "org.springframework.boot", name: "spring-boot", version: "1.4.3.RELEASE"
	compileOnly group: "org.springframework.hateoas", name: "spring-hateoas", version: "0.23.0.RELEASE"
	compileOnly project(":dxp:apps:osb:osb-faro:osb-faro-api")
	compileOnly project(":dxp:apps:osb:osb-faro:osb-faro-contacts-api")
	compileOnly project(":dxp:apps:osb:osb-faro:osb-faro-engine-client")
}