dependencies {
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation project(":apps:blogs:blogs-api")
	testIntegrationImplementation project(":apps:blogs:blogs-test-util")
	testIntegrationImplementation project(":apps:message-boards:message-boards-api")
	testIntegrationImplementation project(":apps:portal-search:portal-search-test-util")
	testIntegrationImplementation project(":apps:subscription:subscription-api")
	testIntegrationImplementation project(":apps:trash:trash-api")
	testIntegrationImplementation project(":apps:trash:trash-test-util")
}