BEGIN;

ALTER TABLE CustomAssetDashboard DROP CONSTRAINT IF EXISTS CHANNELID_FKEY;
ALTER TABLE CustomAssetDashboard ADD CONSTRAINT CHANNELID_FKEY FOREIGN KEY (channelId) REFERENCES Channel ON DELETE CASCADE;

ALTER TABLE DataControlTask ADD COLUMN continueDate TIMESTAMPTZ;
ALTER TABLE DataControlTask ADD COLUMN userId TEXT;
ALTER TABLE DataControlTask ADD COLUMN userName TEXT;

ALTER TABLE Experiment ADD CONSTRAINT CHANNELID_FKEY FOREIGN KEY (channelId) REFERENCES Channel ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS AuditEvent (
	id BIGSERIAL PRIMARY KEY,
	context TEXT,
	createDate TIMESTAMPTZ,
	type TEXT,
	userId TEXT,
	userName TEXT
);

COMMIT;