logging.level.org.jooq.tools.LoggerListener=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=TRACE
management.security.enabled=false
osb.asah.backend.temp.path=./
spring.datasource.hikari.maximum-pool-size=3