dependencies {
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.19"
	testIntegrationImplementation project(":apps:message-boards:message-boards-api")
	testIntegrationImplementation project(":apps:portal-search:portal-search-test-util")
	testIntegrationImplementation project(":apps:social:social-activity-test-util")
	testIntegrationImplementation project(":apps:trash:trash-api")
	testIntegrationImplementation project(":apps:trash:trash-test-util")
	testIntegrationImplementation project(":core:registry-api")
}