/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.commerce.cloud.client.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.commerce.cloud.client.model.CommerceCloudForecastOrder;
import com.liferay.commerce.cloud.client.model.CommerceCloudForecastOrderModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CommerceCloudForecastOrder service. Represents a row in the &quot;CommerceCloudForecastOrder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CommerceCloudForecastOrderModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceCloudForecastOrderImpl}.
 * </p>
 *
 * @author Andrea Di Giorgi
 * @see CommerceCloudForecastOrderImpl
 * @generated
 */
@ProviderType
public class CommerceCloudForecastOrderModelImpl
	extends BaseModelImpl<CommerceCloudForecastOrder>
	implements CommerceCloudForecastOrderModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce cloud forecast order model instance should use the <code>CommerceCloudForecastOrder</code> interface instead.
	 */
	public static final String TABLE_NAME = "CommerceCloudForecastOrder";

	public static final Object[][] TABLE_COLUMNS = {
		{"commerceCloudForecastOrderId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"commerceOrderId", Types.BIGINT},
		{"syncDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("commerceCloudForecastOrderId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("commerceOrderId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("syncDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CommerceCloudForecastOrder (commerceCloudForecastOrderId LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,commerceOrderId LONG,syncDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table CommerceCloudForecastOrder";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commerceCloudForecastOrder.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CommerceCloudForecastOrder.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.cloud.client.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.commerce.cloud.client.model.CommerceCloudForecastOrder"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.cloud.client.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.commerce.cloud.client.model.CommerceCloudForecastOrder"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.cloud.client.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.commerce.cloud.client.model.CommerceCloudForecastOrder"),
		true);

	public static final long COMMERCEORDERID_COLUMN_BITMASK = 1L;

	public static final long SYNCDATE_COLUMN_BITMASK = 2L;

	public static final long CREATEDATE_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.commerce.cloud.client.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.commerce.cloud.client.model.CommerceCloudForecastOrder"));

	public CommerceCloudForecastOrderModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commerceCloudForecastOrderId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommerceCloudForecastOrderId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commerceCloudForecastOrderId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommerceCloudForecastOrder.class;
	}

	@Override
	public String getModelClassName() {
		return CommerceCloudForecastOrder.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CommerceCloudForecastOrder, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CommerceCloudForecastOrder, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceCloudForecastOrder, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(CommerceCloudForecastOrder)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CommerceCloudForecastOrder, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CommerceCloudForecastOrder, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CommerceCloudForecastOrder)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CommerceCloudForecastOrder, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CommerceCloudForecastOrder, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CommerceCloudForecastOrder>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CommerceCloudForecastOrder.class.getClassLoader(),
			CommerceCloudForecastOrder.class, ModelWrapper.class);

		try {
			Constructor<CommerceCloudForecastOrder> constructor =
				(Constructor<CommerceCloudForecastOrder>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map
		<String, Function<CommerceCloudForecastOrder, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<CommerceCloudForecastOrder, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<CommerceCloudForecastOrder, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CommerceCloudForecastOrder, Object>>();
		Map<String, BiConsumer<CommerceCloudForecastOrder, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<CommerceCloudForecastOrder, ?>>();

		attributeGetterFunctions.put(
			"commerceCloudForecastOrderId",
			new Function<CommerceCloudForecastOrder, Object>() {

				@Override
				public Object apply(
					CommerceCloudForecastOrder commerceCloudForecastOrder) {

					return commerceCloudForecastOrder.
						getCommerceCloudForecastOrderId();
				}

			});
		attributeSetterBiConsumers.put(
			"commerceCloudForecastOrderId",
			new BiConsumer<CommerceCloudForecastOrder, Object>() {

				@Override
				public void accept(
					CommerceCloudForecastOrder commerceCloudForecastOrder,
					Object commerceCloudForecastOrderId) {

					commerceCloudForecastOrder.setCommerceCloudForecastOrderId(
						(Long)commerceCloudForecastOrderId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<CommerceCloudForecastOrder, Object>() {

				@Override
				public Object apply(
					CommerceCloudForecastOrder commerceCloudForecastOrder) {

					return commerceCloudForecastOrder.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<CommerceCloudForecastOrder, Object>() {

				@Override
				public void accept(
					CommerceCloudForecastOrder commerceCloudForecastOrder,
					Object groupId) {

					commerceCloudForecastOrder.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<CommerceCloudForecastOrder, Object>() {

				@Override
				public Object apply(
					CommerceCloudForecastOrder commerceCloudForecastOrder) {

					return commerceCloudForecastOrder.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<CommerceCloudForecastOrder, Object>() {

				@Override
				public void accept(
					CommerceCloudForecastOrder commerceCloudForecastOrder,
					Object companyId) {

					commerceCloudForecastOrder.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<CommerceCloudForecastOrder, Object>() {

				@Override
				public Object apply(
					CommerceCloudForecastOrder commerceCloudForecastOrder) {

					return commerceCloudForecastOrder.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<CommerceCloudForecastOrder, Object>() {

				@Override
				public void accept(
					CommerceCloudForecastOrder commerceCloudForecastOrder,
					Object createDate) {

					commerceCloudForecastOrder.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"commerceOrderId",
			new Function<CommerceCloudForecastOrder, Object>() {

				@Override
				public Object apply(
					CommerceCloudForecastOrder commerceCloudForecastOrder) {

					return commerceCloudForecastOrder.getCommerceOrderId();
				}

			});
		attributeSetterBiConsumers.put(
			"commerceOrderId",
			new BiConsumer<CommerceCloudForecastOrder, Object>() {

				@Override
				public void accept(
					CommerceCloudForecastOrder commerceCloudForecastOrder,
					Object commerceOrderId) {

					commerceCloudForecastOrder.setCommerceOrderId(
						(Long)commerceOrderId);
				}

			});
		attributeGetterFunctions.put(
			"syncDate",
			new Function<CommerceCloudForecastOrder, Object>() {

				@Override
				public Object apply(
					CommerceCloudForecastOrder commerceCloudForecastOrder) {

					return commerceCloudForecastOrder.getSyncDate();
				}

			});
		attributeSetterBiConsumers.put(
			"syncDate",
			new BiConsumer<CommerceCloudForecastOrder, Object>() {

				@Override
				public void accept(
					CommerceCloudForecastOrder commerceCloudForecastOrder,
					Object syncDate) {

					commerceCloudForecastOrder.setSyncDate((Date)syncDate);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getCommerceCloudForecastOrderId() {
		return _commerceCloudForecastOrderId;
	}

	@Override
	public void setCommerceCloudForecastOrderId(
		long commerceCloudForecastOrderId) {

		_commerceCloudForecastOrderId = commerceCloudForecastOrderId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public long getCommerceOrderId() {
		return _commerceOrderId;
	}

	@Override
	public void setCommerceOrderId(long commerceOrderId) {
		_columnBitmask |= COMMERCEORDERID_COLUMN_BITMASK;

		if (!_setOriginalCommerceOrderId) {
			_setOriginalCommerceOrderId = true;

			_originalCommerceOrderId = _commerceOrderId;
		}

		_commerceOrderId = commerceOrderId;
	}

	public long getOriginalCommerceOrderId() {
		return _originalCommerceOrderId;
	}

	@Override
	public Date getSyncDate() {
		return _syncDate;
	}

	@Override
	public void setSyncDate(Date syncDate) {
		_columnBitmask |= SYNCDATE_COLUMN_BITMASK;

		if (_originalSyncDate == null) {
			_originalSyncDate = _syncDate;
		}

		_syncDate = syncDate;
	}

	public Date getOriginalSyncDate() {
		return _originalSyncDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CommerceCloudForecastOrder.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommerceCloudForecastOrder toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommerceCloudForecastOrderImpl commerceCloudForecastOrderImpl =
			new CommerceCloudForecastOrderImpl();

		commerceCloudForecastOrderImpl.setCommerceCloudForecastOrderId(
			getCommerceCloudForecastOrderId());
		commerceCloudForecastOrderImpl.setGroupId(getGroupId());
		commerceCloudForecastOrderImpl.setCompanyId(getCompanyId());
		commerceCloudForecastOrderImpl.setCreateDate(getCreateDate());
		commerceCloudForecastOrderImpl.setCommerceOrderId(getCommerceOrderId());
		commerceCloudForecastOrderImpl.setSyncDate(getSyncDate());

		commerceCloudForecastOrderImpl.resetOriginalValues();

		return commerceCloudForecastOrderImpl;
	}

	@Override
	public int compareTo(
		CommerceCloudForecastOrder commerceCloudForecastOrder) {

		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), commerceCloudForecastOrder.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CommerceCloudForecastOrder)) {
			return false;
		}

		CommerceCloudForecastOrder commerceCloudForecastOrder =
			(CommerceCloudForecastOrder)obj;

		long primaryKey = commerceCloudForecastOrder.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CommerceCloudForecastOrderModelImpl
			commerceCloudForecastOrderModelImpl = this;

		commerceCloudForecastOrderModelImpl._originalCommerceOrderId =
			commerceCloudForecastOrderModelImpl._commerceOrderId;

		commerceCloudForecastOrderModelImpl._setOriginalCommerceOrderId = false;

		commerceCloudForecastOrderModelImpl._originalSyncDate =
			commerceCloudForecastOrderModelImpl._syncDate;

		commerceCloudForecastOrderModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CommerceCloudForecastOrder> toCacheModel() {
		CommerceCloudForecastOrderCacheModel
			commerceCloudForecastOrderCacheModel =
				new CommerceCloudForecastOrderCacheModel();

		commerceCloudForecastOrderCacheModel.commerceCloudForecastOrderId =
			getCommerceCloudForecastOrderId();

		commerceCloudForecastOrderCacheModel.groupId = getGroupId();

		commerceCloudForecastOrderCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			commerceCloudForecastOrderCacheModel.createDate =
				createDate.getTime();
		}
		else {
			commerceCloudForecastOrderCacheModel.createDate = Long.MIN_VALUE;
		}

		commerceCloudForecastOrderCacheModel.commerceOrderId =
			getCommerceOrderId();

		Date syncDate = getSyncDate();

		if (syncDate != null) {
			commerceCloudForecastOrderCacheModel.syncDate = syncDate.getTime();
		}
		else {
			commerceCloudForecastOrderCacheModel.syncDate = Long.MIN_VALUE;
		}

		return commerceCloudForecastOrderCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CommerceCloudForecastOrder, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CommerceCloudForecastOrder, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceCloudForecastOrder, Object>
				attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply(
					(CommerceCloudForecastOrder)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CommerceCloudForecastOrder, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CommerceCloudForecastOrder, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceCloudForecastOrder, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(CommerceCloudForecastOrder)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, CommerceCloudForecastOrder>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	private long _commerceCloudForecastOrderId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private long _commerceOrderId;
	private long _originalCommerceOrderId;
	private boolean _setOriginalCommerceOrderId;
	private Date _syncDate;
	private Date _originalSyncDate;
	private long _columnBitmask;
	private CommerceCloudForecastOrder _escapedModel;

}