dependencies {
	compileOnly group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.5.0"
	compileOnly group: "com.liferay.commerce", name: "com.liferay.commerce.product.api", version: "9.0.0-20190606.214810-1"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "3.0.0"
	compileOnly group: "org.osgi", name: "org.osgi.core", version: "6.0.0"
}