/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.commerce.forecast.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.commerce.forecast.model.CommerceForecastValue;
import com.liferay.commerce.forecast.model.CommerceForecastValueModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.math.BigDecimal;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CommerceForecastValue service. Represents a row in the &quot;CommerceForecastValue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CommerceForecastValueModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceForecastValueImpl}.
 * </p>
 *
 * @author Andrea Di Giorgi
 * @see CommerceForecastValueImpl
 * @generated
 */
@ProviderType
public class CommerceForecastValueModelImpl
	extends BaseModelImpl<CommerceForecastValue>
	implements CommerceForecastValueModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce forecast value model instance should use the <code>CommerceForecastValue</code> interface instead.
	 */
	public static final String TABLE_NAME = "CommerceForecastValue";

	public static final Object[][] TABLE_COLUMNS = {
		{"commerceForecastValueId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"commerceForecastEntryId", Types.BIGINT}, {"time_", Types.BIGINT},
		{"lowerValue", Types.DECIMAL}, {"value", Types.DECIMAL},
		{"upperValue", Types.DECIMAL}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("commerceForecastValueId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("commerceForecastEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("time_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lowerValue", Types.DECIMAL);
		TABLE_COLUMNS_MAP.put("value", Types.DECIMAL);
		TABLE_COLUMNS_MAP.put("upperValue", Types.DECIMAL);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CommerceForecastValue (commerceForecastValueId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,commerceForecastEntryId LONG,time_ LONG,lowerValue DECIMAL(30, 16) null,value DECIMAL(30, 16) null,upperValue DECIMAL(30, 16) null)";

	public static final String TABLE_SQL_DROP =
		"drop table CommerceForecastValue";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commerceForecastValue.time ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CommerceForecastValue.time_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.forecast.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.commerce.forecast.model.CommerceForecastValue"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.forecast.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.commerce.forecast.model.CommerceForecastValue"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.commerce.forecast.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.commerce.forecast.model.CommerceForecastValue"),
		true);

	public static final long COMMERCEFORECASTENTRYID_COLUMN_BITMASK = 1L;

	public static final long TIME_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.commerce.forecast.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.commerce.forecast.model.CommerceForecastValue"));

	public CommerceForecastValueModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commerceForecastValueId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommerceForecastValueId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commerceForecastValueId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommerceForecastValue.class;
	}

	@Override
	public String getModelClassName() {
		return CommerceForecastValue.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CommerceForecastValue, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CommerceForecastValue, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceForecastValue, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CommerceForecastValue)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CommerceForecastValue, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CommerceForecastValue, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CommerceForecastValue)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CommerceForecastValue, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CommerceForecastValue, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CommerceForecastValue>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CommerceForecastValue.class.getClassLoader(),
			CommerceForecastValue.class, ModelWrapper.class);

		try {
			Constructor<CommerceForecastValue> constructor =
				(Constructor<CommerceForecastValue>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<CommerceForecastValue, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CommerceForecastValue, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CommerceForecastValue, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CommerceForecastValue, Object>>();
		Map<String, BiConsumer<CommerceForecastValue, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<CommerceForecastValue, ?>>();

		attributeGetterFunctions.put(
			"commerceForecastValueId",
			new Function<CommerceForecastValue, Object>() {

				@Override
				public Object apply(
					CommerceForecastValue commerceForecastValue) {

					return commerceForecastValue.getCommerceForecastValueId();
				}

			});
		attributeSetterBiConsumers.put(
			"commerceForecastValueId",
			new BiConsumer<CommerceForecastValue, Object>() {

				@Override
				public void accept(
					CommerceForecastValue commerceForecastValue,
					Object commerceForecastValueId) {

					commerceForecastValue.setCommerceForecastValueId(
						(Long)commerceForecastValueId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<CommerceForecastValue, Object>() {

				@Override
				public Object apply(
					CommerceForecastValue commerceForecastValue) {

					return commerceForecastValue.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<CommerceForecastValue, Object>() {

				@Override
				public void accept(
					CommerceForecastValue commerceForecastValue,
					Object companyId) {

					commerceForecastValue.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<CommerceForecastValue, Object>() {

				@Override
				public Object apply(
					CommerceForecastValue commerceForecastValue) {

					return commerceForecastValue.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<CommerceForecastValue, Object>() {

				@Override
				public void accept(
					CommerceForecastValue commerceForecastValue,
					Object userId) {

					commerceForecastValue.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<CommerceForecastValue, Object>() {

				@Override
				public Object apply(
					CommerceForecastValue commerceForecastValue) {

					return commerceForecastValue.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<CommerceForecastValue, Object>() {

				@Override
				public void accept(
					CommerceForecastValue commerceForecastValue,
					Object userName) {

					commerceForecastValue.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<CommerceForecastValue, Object>() {

				@Override
				public Object apply(
					CommerceForecastValue commerceForecastValue) {

					return commerceForecastValue.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<CommerceForecastValue, Object>() {

				@Override
				public void accept(
					CommerceForecastValue commerceForecastValue,
					Object createDate) {

					commerceForecastValue.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<CommerceForecastValue, Object>() {

				@Override
				public Object apply(
					CommerceForecastValue commerceForecastValue) {

					return commerceForecastValue.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<CommerceForecastValue, Object>() {

				@Override
				public void accept(
					CommerceForecastValue commerceForecastValue,
					Object modifiedDate) {

					commerceForecastValue.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"commerceForecastEntryId",
			new Function<CommerceForecastValue, Object>() {

				@Override
				public Object apply(
					CommerceForecastValue commerceForecastValue) {

					return commerceForecastValue.getCommerceForecastEntryId();
				}

			});
		attributeSetterBiConsumers.put(
			"commerceForecastEntryId",
			new BiConsumer<CommerceForecastValue, Object>() {

				@Override
				public void accept(
					CommerceForecastValue commerceForecastValue,
					Object commerceForecastEntryId) {

					commerceForecastValue.setCommerceForecastEntryId(
						(Long)commerceForecastEntryId);
				}

			});
		attributeGetterFunctions.put(
			"time",
			new Function<CommerceForecastValue, Object>() {

				@Override
				public Object apply(
					CommerceForecastValue commerceForecastValue) {

					return commerceForecastValue.getTime();
				}

			});
		attributeSetterBiConsumers.put(
			"time",
			new BiConsumer<CommerceForecastValue, Object>() {

				@Override
				public void accept(
					CommerceForecastValue commerceForecastValue, Object time) {

					commerceForecastValue.setTime((Long)time);
				}

			});
		attributeGetterFunctions.put(
			"lowerValue",
			new Function<CommerceForecastValue, Object>() {

				@Override
				public Object apply(
					CommerceForecastValue commerceForecastValue) {

					return commerceForecastValue.getLowerValue();
				}

			});
		attributeSetterBiConsumers.put(
			"lowerValue",
			new BiConsumer<CommerceForecastValue, Object>() {

				@Override
				public void accept(
					CommerceForecastValue commerceForecastValue,
					Object lowerValue) {

					commerceForecastValue.setLowerValue((BigDecimal)lowerValue);
				}

			});
		attributeGetterFunctions.put(
			"value",
			new Function<CommerceForecastValue, Object>() {

				@Override
				public Object apply(
					CommerceForecastValue commerceForecastValue) {

					return commerceForecastValue.getValue();
				}

			});
		attributeSetterBiConsumers.put(
			"value",
			new BiConsumer<CommerceForecastValue, Object>() {

				@Override
				public void accept(
					CommerceForecastValue commerceForecastValue, Object value) {

					commerceForecastValue.setValue((BigDecimal)value);
				}

			});
		attributeGetterFunctions.put(
			"upperValue",
			new Function<CommerceForecastValue, Object>() {

				@Override
				public Object apply(
					CommerceForecastValue commerceForecastValue) {

					return commerceForecastValue.getUpperValue();
				}

			});
		attributeSetterBiConsumers.put(
			"upperValue",
			new BiConsumer<CommerceForecastValue, Object>() {

				@Override
				public void accept(
					CommerceForecastValue commerceForecastValue,
					Object upperValue) {

					commerceForecastValue.setUpperValue((BigDecimal)upperValue);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getCommerceForecastValueId() {
		return _commerceForecastValueId;
	}

	@Override
	public void setCommerceForecastValueId(long commerceForecastValueId) {
		_commerceForecastValueId = commerceForecastValueId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCommerceForecastEntryId() {
		return _commerceForecastEntryId;
	}

	@Override
	public void setCommerceForecastEntryId(long commerceForecastEntryId) {
		_columnBitmask |= COMMERCEFORECASTENTRYID_COLUMN_BITMASK;

		if (!_setOriginalCommerceForecastEntryId) {
			_setOriginalCommerceForecastEntryId = true;

			_originalCommerceForecastEntryId = _commerceForecastEntryId;
		}

		_commerceForecastEntryId = commerceForecastEntryId;
	}

	public long getOriginalCommerceForecastEntryId() {
		return _originalCommerceForecastEntryId;
	}

	@Override
	public long getTime() {
		return _time;
	}

	@Override
	public void setTime(long time) {
		_columnBitmask = -1L;

		if (!_setOriginalTime) {
			_setOriginalTime = true;

			_originalTime = _time;
		}

		_time = time;
	}

	public long getOriginalTime() {
		return _originalTime;
	}

	@Override
	public BigDecimal getLowerValue() {
		return _lowerValue;
	}

	@Override
	public void setLowerValue(BigDecimal lowerValue) {
		_lowerValue = lowerValue;
	}

	@Override
	public BigDecimal getValue() {
		return _value;
	}

	@Override
	public void setValue(BigDecimal value) {
		_value = value;
	}

	@Override
	public BigDecimal getUpperValue() {
		return _upperValue;
	}

	@Override
	public void setUpperValue(BigDecimal upperValue) {
		_upperValue = upperValue;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CommerceForecastValue.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommerceForecastValue toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommerceForecastValueImpl commerceForecastValueImpl =
			new CommerceForecastValueImpl();

		commerceForecastValueImpl.setCommerceForecastValueId(
			getCommerceForecastValueId());
		commerceForecastValueImpl.setCompanyId(getCompanyId());
		commerceForecastValueImpl.setUserId(getUserId());
		commerceForecastValueImpl.setUserName(getUserName());
		commerceForecastValueImpl.setCreateDate(getCreateDate());
		commerceForecastValueImpl.setModifiedDate(getModifiedDate());
		commerceForecastValueImpl.setCommerceForecastEntryId(
			getCommerceForecastEntryId());
		commerceForecastValueImpl.setTime(getTime());
		commerceForecastValueImpl.setLowerValue(getLowerValue());
		commerceForecastValueImpl.setValue(getValue());
		commerceForecastValueImpl.setUpperValue(getUpperValue());

		commerceForecastValueImpl.resetOriginalValues();

		return commerceForecastValueImpl;
	}

	@Override
	public int compareTo(CommerceForecastValue commerceForecastValue) {
		int value = 0;

		if (getTime() < commerceForecastValue.getTime()) {
			value = -1;
		}
		else if (getTime() > commerceForecastValue.getTime()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CommerceForecastValue)) {
			return false;
		}

		CommerceForecastValue commerceForecastValue =
			(CommerceForecastValue)obj;

		long primaryKey = commerceForecastValue.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CommerceForecastValueModelImpl commerceForecastValueModelImpl = this;

		commerceForecastValueModelImpl._setModifiedDate = false;

		commerceForecastValueModelImpl._originalCommerceForecastEntryId =
			commerceForecastValueModelImpl._commerceForecastEntryId;

		commerceForecastValueModelImpl._setOriginalCommerceForecastEntryId =
			false;

		commerceForecastValueModelImpl._originalTime =
			commerceForecastValueModelImpl._time;

		commerceForecastValueModelImpl._setOriginalTime = false;

		commerceForecastValueModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CommerceForecastValue> toCacheModel() {
		CommerceForecastValueCacheModel commerceForecastValueCacheModel =
			new CommerceForecastValueCacheModel();

		commerceForecastValueCacheModel.commerceForecastValueId =
			getCommerceForecastValueId();

		commerceForecastValueCacheModel.companyId = getCompanyId();

		commerceForecastValueCacheModel.userId = getUserId();

		commerceForecastValueCacheModel.userName = getUserName();

		String userName = commerceForecastValueCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			commerceForecastValueCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			commerceForecastValueCacheModel.createDate = createDate.getTime();
		}
		else {
			commerceForecastValueCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			commerceForecastValueCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			commerceForecastValueCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		commerceForecastValueCacheModel.commerceForecastEntryId =
			getCommerceForecastEntryId();

		commerceForecastValueCacheModel.time = getTime();

		commerceForecastValueCacheModel.lowerValue = getLowerValue();

		commerceForecastValueCacheModel.value = getValue();

		commerceForecastValueCacheModel.upperValue = getUpperValue();

		return commerceForecastValueCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CommerceForecastValue, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CommerceForecastValue, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceForecastValue, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((CommerceForecastValue)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CommerceForecastValue, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CommerceForecastValue, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceForecastValue, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((CommerceForecastValue)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, CommerceForecastValue>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	private long _commerceForecastValueId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _commerceForecastEntryId;
	private long _originalCommerceForecastEntryId;
	private boolean _setOriginalCommerceForecastEntryId;
	private long _time;
	private long _originalTime;
	private boolean _setOriginalTime;
	private BigDecimal _lowerValue;
	private BigDecimal _value;
	private BigDecimal _upperValue;
	private long _columnBitmask;
	private CommerceForecastValue _escapedModel;

}