/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.pricing.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CommercePricingClassRel service. Represents a row in the &quot;CommercePricingClassRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.commerce.pricing.model.impl.CommercePricingClassRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.commerce.pricing.model.impl.CommercePricingClassRelImpl</code>.
 * </p>
 *
 * @author Riccardo Alberti
 * @see CommercePricingClassRel
 * @generated
 */
@ProviderType
public interface CommercePricingClassRelModel
	extends AttachedModel, AuditedModel, BaseModel<CommercePricingClassRel>,
			ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commerce pricing class rel model instance should use the {@link CommercePricingClassRel} interface instead.
	 */

	/**
	 * Returns the primary key of this commerce pricing class rel.
	 *
	 * @return the primary key of this commerce pricing class rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commerce pricing class rel.
	 *
	 * @param primaryKey the primary key of this commerce pricing class rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the commerce pricing class rel ID of this commerce pricing class rel.
	 *
	 * @return the commerce pricing class rel ID of this commerce pricing class rel
	 */
	public long getCommercePricingClassRelId();

	/**
	 * Sets the commerce pricing class rel ID of this commerce pricing class rel.
	 *
	 * @param commercePricingClassRelId the commerce pricing class rel ID of this commerce pricing class rel
	 */
	public void setCommercePricingClassRelId(long commercePricingClassRelId);

	/**
	 * Returns the company ID of this commerce pricing class rel.
	 *
	 * @return the company ID of this commerce pricing class rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this commerce pricing class rel.
	 *
	 * @param companyId the company ID of this commerce pricing class rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this commerce pricing class rel.
	 *
	 * @return the user ID of this commerce pricing class rel
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this commerce pricing class rel.
	 *
	 * @param userId the user ID of this commerce pricing class rel
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this commerce pricing class rel.
	 *
	 * @return the user uuid of this commerce pricing class rel
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this commerce pricing class rel.
	 *
	 * @param userUuid the user uuid of this commerce pricing class rel
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this commerce pricing class rel.
	 *
	 * @return the user name of this commerce pricing class rel
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this commerce pricing class rel.
	 *
	 * @param userName the user name of this commerce pricing class rel
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this commerce pricing class rel.
	 *
	 * @return the create date of this commerce pricing class rel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this commerce pricing class rel.
	 *
	 * @param createDate the create date of this commerce pricing class rel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this commerce pricing class rel.
	 *
	 * @return the modified date of this commerce pricing class rel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this commerce pricing class rel.
	 *
	 * @param modifiedDate the modified date of this commerce pricing class rel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the commerce pricing class ID of this commerce pricing class rel.
	 *
	 * @return the commerce pricing class ID of this commerce pricing class rel
	 */
	public long getCommercePricingClassId();

	/**
	 * Sets the commerce pricing class ID of this commerce pricing class rel.
	 *
	 * @param commercePricingClassId the commerce pricing class ID of this commerce pricing class rel
	 */
	public void setCommercePricingClassId(long commercePricingClassId);

	/**
	 * Returns the fully qualified class name of this commerce pricing class rel.
	 *
	 * @return the fully qualified class name of this commerce pricing class rel
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this commerce pricing class rel.
	 *
	 * @return the class name ID of this commerce pricing class rel
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this commerce pricing class rel.
	 *
	 * @param classNameId the class name ID of this commerce pricing class rel
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this commerce pricing class rel.
	 *
	 * @return the class pk of this commerce pricing class rel
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this commerce pricing class rel.
	 *
	 * @param classPK the class pk of this commerce pricing class rel
	 */
	@Override
	public void setClassPK(long classPK);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CommercePricingClassRel commercePricingClassRel);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CommercePricingClassRel> toCacheModel();

	@Override
	public CommercePricingClassRel toEscapedModel();

	@Override
	public CommercePricingClassRel toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}