task cleanDeployDir(type: Delete)
task deployPublicModules(type: GradleBuild)
task prepareWeDeployModules(type: Copy)
task wedeploy(type: Exec)

File deployConfigsDir = file("wedeploy/lfr/osgi-configs")
File deployDir = file("wedeploy/lfr/deploy")

configurations {
	weDeployModules
}

cleanDeployDir {
	delete deployDir
	delete fileTree(dir: deployConfigsDir, include: "com.liferay.commerce.*.cfg")
}

dependencies {
	weDeployModules subprojects.findAll {
		File lfrbuildPortalFile = it.file(".lfrbuild-portal")

		lfrbuildPortalFile.exists()
	}
}

deployPublicModules {
	dependsOn cleanDeployDir
	dir = new File(rootDir.parentFile, "com-liferay-commerce")

	startParameter.projectProperties = [
		"forced.configs.deploy.dir": deployConfigsDir.absolutePath,
		"forced.deploy.dir": deployDir.absolutePath
	]

	startParameter.parallelProjectExecutionEnabled = true
	startParameter.systemPropertiesArgs = ["build.profile": "portal"]

	tasks = ["deploy"]
}

prepareWeDeployModules {
	dependsOn cleanDeployDir
	dependsOn deployPublicModules

	from configurations.weDeployModules
	into deployDir
}

wedeploy {
	args "deploy"
	args "--project", project.properties["roject"]

	dependsOn prepareWeDeployModules
	description = "Deploys Liferay Commerce to WeDeploy."
	executable = "we"
	group = "upload"
	workingDir = "wedeploy"
}