pom.scm.connection=scm:git:git@github.com:liferay/com-liferay-commerce.git
pom.scm.developerConnection=scm:git:git@github.com:liferay/com-liferay-commerce.git
pom.scm.url=https://github.com/liferay/com-liferay-commerce
project.group=com.liferay.commerce
project.path.prefix=:private:apps:commerce
systemProp.repository.private.password=IsG7rr5egfmbIhFG
systemProp.repository.private.url=https://repository-cdn.liferay.com/nexus/service/local/repo_groups/private/content/
systemProp.repository.private.username=private-20190503