/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.commerce.data.integration.manager.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.commerce.data.integration.manager.model.ScheduledTask;
import com.liferay.commerce.data.integration.manager.service.ScheduledTaskLocalServiceUtil;

/**
 * The extended model base implementation for the ScheduledTask service. Represents a row in the &quot;ScheduledTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ScheduledTaskImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ScheduledTaskImpl
 * @see ScheduledTask
 * @generated
 */
@ProviderType
public abstract class ScheduledTaskBaseImpl extends ScheduledTaskModelImpl
	implements ScheduledTask {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a scheduled task model instance should use the {@link ScheduledTask} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ScheduledTaskLocalServiceUtil.addScheduledTask(this);
		}
		else {
			ScheduledTaskLocalServiceUtil.updateScheduledTask(this);
		}
	}
}